# Phase 1: Data Loading and Initial Exploration

In [ ]:
# Load the raw card, printing, and cardset datasets
import pandas as pd

cards_cardsets = pd.read_csv("/Users/josephkim/Desktop/625/cards_cardsets.csv")
cards = pd.read_csv("/Users/josephkim/Desktop/625/cards.csv")

In [171]:
pd.set_option("display.max_colwidth", None)

### Initial Data Auditing

In [ ]:
# Identify missing values across card attributes
cards.isna().sum()

id                     0
name                   0
type                   0
desc                   0
atk                 4650
def                 5065
level               5065
race                   1
attribute           4650
scale              12933
archetype           5493
linkval            12866
linkmarkers        12866
image_url              0
image_url_small        0
ban_tcg            13086
ban_ocg            13091
ban_goat           13208
staple             13217
views                  0
viewsweek              0
upvotes                0
downvotes              0
formats               13
treated_as         13139
tcg_date             416
ocg_date             400
konami_id            480
has_effect             0
dtype: int64

In [ ]:
# Check unique values to understand column cardinality
cards.nunique()

id                 13281
name               13281
type                  28
desc               13234
atk                   80
def                   75
level                 14
race                  86
attribute              7
scale                 14
archetype            556
linkval                6
linkmarkers           83
image_url          13281
image_url_small    13281
ban_tcg                3
ban_ocg                3
ban_goat               3
staple                 1
views              12680
viewsweek             12
upvotes              134
downvotes             57
formats              111
treated_as           131
tcg_date             604
ocg_date             744
konami_id          12801
has_effect             2
dtype: int64

In [ ]:
# Examine the distribution of card types
cards["type"].value_counts(dropna=False)

type
Effect Monster                     4725
Spell Card                         2592
Trap Card                          1934
Normal Monster                      662
XYZ Monster                         521
Fusion Monster                      479
Tuner Monster                       462
Link Monster                        415
Synchro Monster                     413
Pendulum Effect Monster             273
Flip Effect Monster                 184
Skill Card                          124
Ritual Effect Monster               116
Token                               107
Gemini Monster                       45
Synchro Tuner Monster                41
Union Effect Monster                 39
Pendulum Normal Monster              36
Spirit Monster                       33
Toon Monster                         17
Ritual Monster                       15
Pendulum Effect Fusion Monster       11
XYZ Pendulum Effect Monster          10
Normal Tuner Monster                 10
Pendulum Tuner Effect Monster         8
Synchro Pendulum Effect Monster       7
Pendulum Effect Ritual Monster        1
Pendulum Flip Effect Monster          1
Name: count, dtype: int64

In [ ]:
# Examine the distribution of card attributes
cards["attribute"].value_counts(dropna=False)

attribute
NaN       4650
DARK      2413
EARTH     1972
LIGHT     1768
WATER      898
WIND       801
FIRE       773
DIVINE       6
Name: count, dtype: int64

In [ ]:
# Examine the distribution of restriction status
cards["ban_tcg"].value_counts(dropna=False)

ban_tcg
NaN             13086
Banned            105
Limited            84
Semi-Limited        6
Name: count, dtype: int64

In [177]:
cards["staple"].value_counts(dropna=False)

staple
NaN    13217
Yes       64
Name: count, dtype: int64

In [178]:
cards["viewsweek"].value_counts(dropna=False)

viewsweek
0      12004
26      1146
52        95
78        15
53         6
104        6
130        3
338        2
105        1
208        1
79         1
136        1
Name: count, dtype: int64

In [179]:
cards["has_effect"].value_counts(dropna=False)

has_effect
1    12511
0      770
Name: count, dtype: int64

In [180]:
cards["formats"].value_counts(dropna=False)

formats
TCG|OCG|Master Duel                                                     2299
Duel Links|Common Charity|TCG|OCG|Master Duel                           2189
Common Charity|TCG|OCG|Master Duel                                      1908
Duel Links|TCG|OCG|Master Duel                                          1558
Duel Links|Common Charity|Edison|TCG|OCG|Master Duel                    1037
                                                                        ...
Master Duel                                                                1
Edison|TCG|OCG                                                             1
GOAT|Duel Links|Speed Duel|Common Charity|Edison|TCG|OCG|Master Duel       1
GOAT|OCG GOAT|Duel Links|Common Charity|Edison|Speed Duel|TCG|OCG          1
Speed Duel|Common Charity|OCG                                              1
Name: count, Length: 112, dtype: int64

In [181]:
cards["treated_as"].dropna().head(20)

22                                Umi
115                    Acid Trap Hole
197              Aleister the Invoker
501     Apollousa, Bow of the Goddess
564               Arcana Knight Joker
723       Ash Blossom & Joyous Spring
897                     Barrel Dragon
1143                Black Rose Dragon
1308        Blue-Eyes Ultimate Dragon
1309           Blue-Eyes White Dragon
1359                 Borreload Dragon
1364               Borrelsword Dragon
1547                    Buster Blader
1682                  Celtic Guardian
1744           Chaos Dragon Levianeer
1890        Clear Wing Synchro Dragon
2156                 Crush Card Virus
2266                     Cyber Dragon
2270            Cyber Dragon Infinity
2279                 Cyber End Dragon
Name: treated_as, dtype: object

In [182]:
cards[["views", "upvotes", "downvotes"]].describe()

              views       upvotes     downvotes
count  1.328100e+04  13281.000000  13281.000000
mean   1.187238e+05      6.715759      1.347263
std    2.974221e+05     36.563359      6.566197
min    0.000000e+00      0.000000      0.000000
25%    2.347300e+04      1.000000      0.000000
50%    5.012200e+04      3.000000      0.000000
75%    1.163900e+05      6.000000      2.000000
max    1.424656e+07   2608.000000    533.000000

In [ ]:
# Remove columns that are not needed for card analysis
new_cards = cards.drop(columns=['viewsweek', 'konami_id','staple'])

In [184]:
new_cards[new_cards["has_effect"] == 0]

,id,name,type,desc,atk,def,level,race,attribute,scale,...,ban_ocg,ban_goat,views,upvotes,downvotes,formats,treated_as,tcg_date,ocg_date,has_effect
10,11714098,"30,000-Year White Turtle",Normal Monster,"A huge turtle that has existed for more than 30,000 years.",1250.0,2100.0,5.0,Aqua,WATER,NaN,...,NaN,NaN,147392,33,16,OCG GOAT|Duel Links|OCG|Master Duel,NaN,NaN,1999-10-17,0
13,23771716,7 Colored Fish,Normal Monster,A rare rainbow fish that has never been caught by mortal man.,1800.0,800.0,4.0,Fish,WATER,NaN,...,NaN,NaN,356795,26,6,GOAT|OCG GOAT|Duel Links|Common Charity|Edison|Speed Duel|TCG|OCG|Master Duel,NaN,2002-06-26,2000-01-27,0
78,40387124,Abyss Flower,Normal Monster,A rarely seen flower that blossoms quietly on the edge of darkness.,750.0,400.0,2.0,Plant,EARTH,NaN,...,NaN,NaN,14579,4,4,OCG GOAT|Duel Links|OCG|Master Duel,NaN,NaN,1999-05-25,0
113,77568553,Acid Crawler,Normal Monster,A giant caterpillar that secretes an acid mist that melts anything.,900.0,700.0,3.0,Insect,EARTH,NaN,...,NaN,NaN,13034,6,3,OCG GOAT|Duel Links|OCG|Master Duel,NaN,NaN,1999-09-23,0
118,47372349,Acrobat Monkey,Normal Monster,An autonomous monkey type robot which was developed with cutting-edge technology. It moves very acrobatically.,1000.0,1800.0,3.0,Machine,EARTH,NaN,...,NaN,NaN,41402,4,2,GOAT|OCG GOAT|Duel Links|Common Charity|Edison|TCG|OCG|Master Duel,NaN,2003-12-01,2002-11-21,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13220,69123138,Zera the Mant,Ritual Monster,"This card can only be Ritual Summoned with the Ritual Spell Card, ""Zera Ritual"".",2800.0,2300.0,8.0,Fiend,DARK,NaN,...,NaN,NaN,32588,7,0,OCG GOAT|Duel Links|Edison|Common Charity|TCG|OCG|Master Duel,NaN,2007-07-26,1999-12-18,0
13235,24311372,Zoa,Normal Monster,"A monster whose full potential can be achieved when outfitted with ""Metalmorph"".",2600.0,1900.0,7.0,Fiend,DARK,NaN,...,NaN,NaN,39154,9,0,GOAT|OCG GOAT|Duel Links|Common Charity|Edison|TCG|OCG|Master Duel,NaN,2003-11-04,1999-12-09,0
13249,31339260,Zombie Warrior,Fusion Monster,"""Skull Servant"" + ""Battle Warrior""",1200.0,900.0,3.0,Zombie,DARK,NaN,...,NaN,NaN,50419,3,1,OCG GOAT|Duel Links|TCG|OCG|Master Duel,NaN,2016-03-18,1999-03-27,0
13252,14575467,Zombino,Normal Monster,The two are so close\r\nThey die and return to life\r\nInseparable,2000.0,0.0,4.0,Zombie,EARTH,NaN,...,NaN,NaN,29065,6,1,Duel Links|Common Charity|TCG|OCG|Master Duel,NaN,2018-02-01,2017-10-14,0
13278,7459013,"Zure, Knight of Dark World",Normal Monster,The name of this illustrious knight is known by all residents of Dark World. He never oppresses the commoners.,1800.0,1500.0,4.0,Fiend,DARK,NaN,...,NaN,NaN,68294,5,0,Duel Links|Common Charity|Edison|TCG|OCG|Master Duel,NaN,2005-11-05,2005-08-11,0

In [185]:
new_cards[new_cards["has_effect"] == 0]["type"].value_counts()

type
Normal Monster             651
Fusion Monster              60
Pendulum Normal Monster     34
Ritual Monster              15
Link Monster                 5
Synchro Monster              3
XYZ Monster                  2
Name: count, dtype: int64

## Card Cleaning and Filtering

In [ ]:
# Exclude cards marked as banned in the source data
new_cards = new_cards[new_cards["ban_tcg"] != "Banned"].copy()

In [187]:
new_cards["ban_tcg"].value_counts(dropna=False)

ban_tcg
NaN             13086
Limited            84
Semi-Limited        6
Name: count, dtype: int64

In [188]:
new_cards.shape

(13176, 26)

In [189]:
# 1. Duplicate IDs
new_cards["id"].duplicated().sum()

0

In [190]:
# 2. Duplicate names
new_cards["name"].duplicated().sum()

0

In [191]:
# 3. Card types remaining
new_cards["type"].value_counts()

type
Effect Monster                     4703
Spell Card                         2568
Trap Card                          1921
Normal Monster                      662
XYZ Monster                         507
Fusion Monster                      476
Tuner Monster                       458
Synchro Monster                     409
Link Monster                        396
Pendulum Effect Monster             272
Flip Effect Monster                 183
Skill Card                          124
Ritual Effect Monster               116
Token                               107
Gemini Monster                       45
Synchro Tuner Monster                41
Union Effect Monster                 39
Pendulum Normal Monster              36
Spirit Monster                       33
Toon Monster                         17
Ritual Monster                       15
Pendulum Effect Fusion Monster       11
XYZ Pendulum Effect Monster          10
Normal Tuner Monster                 10
Pendulum Tuner Effect Monster         8
Synchro Pendulum Effect Monster       7
Pendulum Effect Ritual Monster        1
Pendulum Flip Effect Monster          1
Name: count, dtype: int64

In [192]:
# 4. Archetype coverage
new_cards["archetype"].value_counts(dropna=False).head(20)

archetype
NaN                5435
Elemental HERO      133
Performapal          90
Archfiend            89
Blackwing            80
D/D                  65
Gladiator Beast      56
Roid                 54
Ninja                52
Six Samurai          52
Raidraptor           52
Dark Magician        52
Noble Knight         51
Destiny HERO         49
Salamangreat         47
Genex                46
Ice Barrier          46
Chaos                46
Naturia              45
Koa'ki Meiru         45
Name: count, dtype: int64

In [193]:
# 5. TCG release date range
new_cards["tcg_date"] = pd.to_datetime(new_cards["tcg_date"])
new_cards["tcg_date"].min(), new_cards["tcg_date"].max()

(Timestamp('2001-01-01 00:00:00'), Timestamp('2024-07-18 00:00:00'))

In [194]:
# 6. Check ATK/DEF for weird values
new_cards[["atk", "def", "level"]].describe()

               atk          def        level
count  8563.000000  8167.000000  8167.000000
mean   1484.666589  1254.886739     4.595690
std     950.373310   872.706684     2.413555
min       0.000000     0.000000     0.000000
25%     800.000000   500.000000     3.000000
50%    1500.000000  1200.000000     4.000000
75%    2200.000000  1900.000000     6.000000
max    5000.000000  5000.000000    13.000000

In [195]:
# 7. Remaining banlist categories
new_cards["ban_tcg"].value_counts(dropna=False)

ban_tcg
NaN             13086
Limited            84
Semi-Limited        6
Name: count, dtype: int64

In [ ]:
# Extract release year for chronological analysis
new_cards["release_year"] = new_cards["tcg_date"].dt.year

## Card-Printing Relationship and Merge

### Investigations of cards_cardsets

In [197]:
cards_cardsets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36880 entries, 0 to 36879
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   card_id          36880 non-null  int64
 1   set_id           36880 non-null  object
 2   set_code         36880 non-null  object
 3   set_rarity       36880 non-null  object
 4   set_rarity_code  36562 non-null  object
dtypes: int64(1), object(4)
memory usage: 1.4+ MB

In [198]:
cards_cardsets.isna().sum()

card_id              0
set_id               0
set_code             0
set_rarity           0
set_rarity_code    318
dtype: int64

In [199]:
cards_cardsets.nunique()

card_id            12836
set_id               975
set_code            1251
set_rarity            41
set_rarity_code       29
dtype: int64

In [200]:
cards_cardsets.shape

(36880, 5)

In [201]:
new_cards[new_cards["name"].str.contains("Blackwing")][["id", "name"]].head()

           id                                             name
733  23338098  Assault Blackwing - Chidori the Rain Sprinkling
734  70456282            Assault Blackwing - Kunai the Drizzle
735  80773359   Assault Blackwing - Onimaru the Divine Thunder
736  16051717      Assault Blackwing - Raikiri the Rain Shower
737  17994645          Assault Blackwing - Sayo the Rain Hider

In [202]:
cards_cardsets[cards_cardsets["card_id"] == 23338098]

,card_id,set_id,set_code,set_rarity,set_rarity_code
8708,23338098,b3c2e796543ba88d7aca52cda11c06c4,EN051,Super Rare,(SR)

In [203]:
cards_cardsets["card_id"].value_counts().head(10)

card_id
89631139    63
46986421    60
5318639     57
97077563    52
70095154    44
24094653    42
53129443    39
74677427    39
72302403    38
32807846    37
Name: count, dtype: int64

In [204]:
new_cards[new_cards["id"] == 5318639][["id", "name"]]

           id                    name
7757  5318639  Mystical Space Typhoon

In [ ]:
# Connect cards to their printing records using card IDs
cards_printings = new_cards.merge(
    cards_cardsets,
    left_on="id",
    right_on="card_id",
    how="left"
)

In [206]:
new_cards.shape

(13176, 27)

In [207]:
cards_printings.shape

(36914, 32)

In [208]:
cards_printings["id"].nunique()

13176

## Release-Date Analysis

In [209]:
new_cards.columns

Index(['id', 'name', 'type', 'desc', 'atk', 'def', 'level', 'race',
       'attribute', 'scale', 'archetype', 'linkval', 'linkmarkers',
       'image_url', 'image_url_small', 'ban_tcg', 'ban_ocg', 'ban_goat',
       'views', 'upvotes', 'downvotes', 'formats', 'treated_as', 'tcg_date',
       'ocg_date', 'has_effect', 'release_year'],
      dtype='object')

In [210]:
new_cards[["name", "tcg_date", "release_year"]].head()

                            name   tcg_date  release_year
0       "A" Cell Breeding Device 2007-05-16        2007.0
1             "A" Cell Incubator 2007-11-14        2007.0
2  "A" Cell Recombination Device 2016-11-03        2016.0
3         "A" Cell Scatter Burst 2007-02-28        2007.0
4     "Infernoble Arms - Almace" 2023-07-27        2023.0

# Phase 2: Cardset Validation and Analysis

In [ ]:
# Count cards by their first recorded TCG release year
cards_per_year = (
    new_cards
    .groupby("release_year")
    .size()
    .reset_index(name="cards_released")
)

cards_per_year

    release_year  cards_released
0         2001.0               1
1         2002.0             597
2         2003.0             538
3         2004.0             393
4         2005.0             289
5         2006.0             328
6         2007.0             413
7         2008.0             486
8         2009.0             469
9         2010.0             589
10        2011.0             600
11        2012.0             541
12        2013.0             568
13        2014.0             538
14        2015.0             635
15        2016.0             662
16        2017.0             645
17        2018.0             655
18        2019.0             768
19        2020.0             707
20        2021.0             630
21        2022.0             668
22        2023.0             650
23        2024.0             390

In [212]:
cardsets = pd.read_csv("/Users/josephkim/Desktop/625/cardsets.csv")
cardsets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 977 entries, 0 to 976
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            977 non-null    object
 1   set_name      977 non-null    object
 2   set_code      977 non-null    object
 3   num_of_cards  977 non-null    int64
 4   tcg_date      977 non-null    object
dtypes: int64(1), object(4)
memory usage: 38.3+ KB

In [213]:
cards_cardsets["set_id"].isin(cardsets["id"]).value_counts()

set_id
True    36880
Name: count, dtype: int64

In [214]:
cardsets["id"].isna().sum()

0

In [215]:
cardsets["set_name"].isna().sum()

0

In [216]:
cardsets["num_of_cards"].value_counts(dropna=False)

num_of_cards
1      344
100     57
2       50
4       41
3       40
      ...
432      1
237      1
103      1
235      1
86       1
Name: count, Length: 135, dtype: int64

In [217]:
cardsets["num_of_cards"].value_counts().sort_index().head(10)

num_of_cards
1     344
2      50
3      40
4      41
5       7
6      19
7       2
8       4
9       7
10      6
Name: count, dtype: int64

In [218]:
cardsets["num_of_cards"].isna().sum()

0

In [219]:
cardsets["set_name"].value_counts(dropna=False)

set_name
Summoned Skull Sample promotional card          1
Raging Tempest Sneak Peek Participation Card    1
Fusion Enforcers                                1
Star Pack Battle Royal                          1
Raging Tempest: Special Edition                 1
                                               ..
Shonen Jump Vol. 8, Issue 3 promotional card    1
Duelist Pack Collection Tin 2010                1
Absolute Powerforce: Special Edition            1
Duelist Pack: Kaiba                             1
The Infinite Forbidden                          1
Name: count, Length: 977, dtype: int64

In [220]:
cardsets["tcg_date"].isna().sum()

0

In [221]:
cardsets["tcg_date"] = pd.to_datetime(cardsets["tcg_date"])
cardsets["tcg_date"].min(), cardsets["tcg_date"].max()

(Timestamp('2001-01-01 00:00:00'), Timestamp('2024-07-18 00:00:00'))

In [222]:
cardsets["release_year"] = cardsets["tcg_date"].dt.year

In [223]:
cardsets["num_of_cards"].sum()

34454

In [224]:
cardsets.shape

(977, 6)

In [ ]:
# Count printing records associated with each cardset
set_counts = cards_cardsets.groupby("set_id").size()
set_counts.head()

set_id
004b9eb13e1396d606d21c4f5fed30d7     20
005adeb3ee84ff7785b85e28469ab1f7    228
005eba16ef83bd8139478a7055c438c0    298
0066143555bb13b5699eb5635a28d6a5     27
00e329416fdfe2945d3449ec817d2819     41
dtype: int64

In [226]:
set_counts = set_counts.reset_index(name="actual_card_count")
set_counts

                               set_id  actual_card_count
0    004b9eb13e1396d606d21c4f5fed30d7                 20
1    005adeb3ee84ff7785b85e28469ab1f7                228
2    005eba16ef83bd8139478a7055c438c0                298
3    0066143555bb13b5699eb5635a28d6a5                 27
4    00e329416fdfe2945d3449ec817d2819                 41
..                                ...                ...
970  ff4184f09976c4dc7e40c97540b1b73f                  1
971  ff4847c1e0c6010ef39e7249a8b43787                  1
972  ff9accf348a3c48c7580727c4252827c                  1
973  ffadfa224feba5632c583b9931e2e3a3                  1
974  ffcbf5db530ba2ee01d686fdf633ef3f                  4

[975 rows x 2 columns]

In [ ]:
# Join reported cardset sizes with calculated printing counts
cardsets_check = cardsets.merge(
    set_counts,
    left_on="id",
    right_on="set_id",
    how="left"
)
cardsets_check

,id,set_name,set_code,num_of_cards,tcg_date,release_year,set_id,actual_card_count
0,a9cc1e0613d1b88098a29464879285a2,Summoned Skull Sample promotional card,SDY,1,2001-01-01,2001,a9cc1e0613d1b88098a29464879285a2,1.0
1,8d1bb889266b35581fb2812b9d5f4013,Legend of Blue Eyes White Dragon,LOB,355,2002-03-08,2002,8d1bb889266b35581fb2812b9d5f4013,358.0
2,91883058af5c8218e84c2851f8b65e66,Yu-Gi-Oh! Dark Duel Stories promotional cards,DDS,6,2002-03-19,2002,91883058af5c8218e84c2851f8b65e66,6.0
3,02f27695ca4bdcabb9641d8357fbcb9a,Starter Deck: Kaiba,SDK,96,2002-03-29,2002,02f27695ca4bdcabb9641d8357fbcb9a,96.0
4,d36de46a616f5afc6714a16c2cd44e38,Starter Deck: Yugi,SDY,95,2002-03-29,2002,d36de46a616f5afc6714a16c2cd44e38,95.0
...,...,...,...,...,...,...,...,...
972,647de2b20c9fe9eb747ef1e0198f5c2f,OTS Tournament Pack 25,OP25,27,2024-06-12,2024,647de2b20c9fe9eb747ef1e0198f5c2f,27.0
973,e55036b1e8130a54ff0ab77e402e5d30,The Lost Art Promotion 2024 B,LART,1,2024-06-19,2024,e55036b1e8130a54ff0ab77e402e5d30,1.0
974,9fbc2ae81027208001000dfd2a7d701e,Battles of Legend: Terminal Revenge,BLTR,117,2024-06-20,2024,9fbc2ae81027208001000dfd2a7d701e,139.0
975,c471deb2c4261aaec2a3789e6923603a,The Lost Art Promotion 2024 C,LART,1,2024-07-17,2024,c471deb2c4261aaec2a3789e6923603a,1.0
976,c67dde397462bc8fd39202d742a53bb9,The Infinite Forbidden,INFO,100,2024-07-18,2024,c67dde397462bc8fd39202d742a53bb9,124.0

In [228]:
cardsets_check[
    cardsets_check["num_of_cards"] != cardsets_check["actual_card_count"]
][
    ["set_name", "num_of_cards", "actual_card_count"]
]

                                set_name  num_of_cards  actual_card_count
1       Legend of Blue Eyes White Dragon           355              358.0
5                          Metal Raiders           432              434.0
8                            Spell Ruler           208              209.0
12                     Pharaoh's Servant           315              326.0
18                Labyrinth of Nightmare           315              328.0
..                                   ...           ...                ...
962                 2-Player Starter Set            88               44.0
963                    Phantom Nightmare           101              125.0
970                Legacy of Destruction            86              108.0
974  Battles of Legend: Terminal Revenge           117              139.0
976               The Infinite Forbidden           100              124.0

[162 rows x 3 columns]

In [229]:
matches = (
    cardsets_check["num_of_cards"]
    == cardsets_check["actual_card_count"]
)

matches.value_counts()

True     815
False    162
Name: count, dtype: int64

In [ ]:
# Calculate discrepancies between reported and observed counts
cardsets_check["difference"] = (
    cardsets_check["actual_card_count"]
    - cardsets_check["num_of_cards"]
)

cardsets_check["difference"].value_counts()

difference
 0.0      815
 1.0       25
 4.0       19
 11.0      19
 6.0       13
 15.0      10
 25.0       9
 3.0        9
-1.0        8
 24.0       5
 2.0        5
 22.0       4
 7.0        3
 18.0       2
 10.0       2
 50.0       2
 12.0       2
 220.0      2
 13.0       2
 29.0       1
-14.0       1
 88.0       1
 23.0       1
 28.0       1
 17.0       1
-4.0        1
 143.0      1
 19.0       1
 14.0       1
 37.0       1
-2.0        1
 99.0       1
 49.0       1
 48.0       1
-12.0       1
 212.0      1
 32.0       1
-44.0       1
Name: count, dtype: int64

In [231]:
#difference = 0     → perfect match
#difference > 0     → cards_cardsets has more records
#difference < 0     → cardsets says there should be more

In [232]:
unique_set_counts = (
    cards_cardsets
    .groupby("set_id")["card_id"]
    .nunique()
    .reset_index(name="unique_card_count")
)
unique_set_counts

                               set_id  unique_card_count
0    004b9eb13e1396d606d21c4f5fed30d7                 20
1    005adeb3ee84ff7785b85e28469ab1f7                224
2    005eba16ef83bd8139478a7055c438c0                298
3    0066143555bb13b5699eb5635a28d6a5                 27
4    00e329416fdfe2945d3449ec817d2819                 41
..                                ...                ...
970  ff4184f09976c4dc7e40c97540b1b73f                  1
971  ff4847c1e0c6010ef39e7249a8b43787                  1
972  ff9accf348a3c48c7580727c4252827c                  1
973  ffadfa224feba5632c583b9931e2e3a3                  1
974  ffcbf5db530ba2ee01d686fdf633ef3f                  4

[975 rows x 2 columns]

In [233]:
cardsets_check = cardsets_check.merge(
    unique_set_counts,
    on="set_id",
    how="left"
)
cardsets_check

,id,set_name,set_code,num_of_cards,tcg_date,release_year,set_id,actual_card_count,difference,unique_card_count
0,a9cc1e0613d1b88098a29464879285a2,Summoned Skull Sample promotional card,SDY,1,2001-01-01,2001,a9cc1e0613d1b88098a29464879285a2,1.0,0.0,1.0
1,8d1bb889266b35581fb2812b9d5f4013,Legend of Blue Eyes White Dragon,LOB,355,2002-03-08,2002,8d1bb889266b35581fb2812b9d5f4013,358.0,3.0,126.0
2,91883058af5c8218e84c2851f8b65e66,Yu-Gi-Oh! Dark Duel Stories promotional cards,DDS,6,2002-03-19,2002,91883058af5c8218e84c2851f8b65e66,6.0,0.0,6.0
3,02f27695ca4bdcabb9641d8357fbcb9a,Starter Deck: Kaiba,SDK,96,2002-03-29,2002,02f27695ca4bdcabb9641d8357fbcb9a,96.0,0.0,50.0
4,d36de46a616f5afc6714a16c2cd44e38,Starter Deck: Yugi,SDY,95,2002-03-29,2002,d36de46a616f5afc6714a16c2cd44e38,95.0,0.0,50.0
...,...,...,...,...,...,...,...,...,...,...
972,647de2b20c9fe9eb747ef1e0198f5c2f,OTS Tournament Pack 25,OP25,27,2024-06-12,2024,647de2b20c9fe9eb747ef1e0198f5c2f,27.0,0.0,27.0
973,e55036b1e8130a54ff0ab77e402e5d30,The Lost Art Promotion 2024 B,LART,1,2024-06-19,2024,e55036b1e8130a54ff0ab77e402e5d30,1.0,0.0,1.0
974,9fbc2ae81027208001000dfd2a7d701e,Battles of Legend: Terminal Revenge,BLTR,117,2024-06-20,2024,9fbc2ae81027208001000dfd2a7d701e,139.0,22.0,113.0
975,c471deb2c4261aaec2a3789e6923603a,The Lost Art Promotion 2024 C,LART,1,2024-07-17,2024,c471deb2c4261aaec2a3789e6923603a,1.0,0.0,1.0
976,c67dde397462bc8fd39202d742a53bb9,The Infinite Forbidden,INFO,100,2024-07-18,2024,c67dde397462bc8fd39202d742a53bb9,124.0,24.0,100.0

In [234]:
cardsets_check[
    ["set_name", "num_of_cards", "actual_card_count", "unique_card_count"]
].head(20)

,set_name,num_of_cards,actual_card_count,unique_card_count
0,Summoned Skull Sample promotional card,1,1.0,1.0
1,Legend of Blue Eyes White Dragon,355,358.0,126.0
2,Yu-Gi-Oh! Dark Duel Stories promotional cards,6,6.0,6.0
3,Starter Deck: Kaiba,96,96.0,50.0
4,Starter Deck: Yugi,95,95.0,50.0
5,Metal Raiders,432,434.0,144.0
6,Tournament Pack: 1st Season,60,60.0,30.0
7,Magic Ruler,235,235.0,131.0
8,Spell Ruler,208,209.0,104.0
9,Tournament Pack: 2nd Season,30,30.0,30.0
10,Booster Pack Collectors Tins 2002,6,6.0,6.0
11,Yu-Gi-Oh! The Eternal Duelist Soul promotional cards,3,3.0,3.0
12,Pharaoh's Servant,315,326.0,105.0
13,Yu-Gi-Oh! Forbidden Memories promotional cards,3,3.0,3.0
14,"Shonen Jump Vol. 1, Issue 1 promotional card",1,1.0,1.0
15,McDonald's Promotional Cards,15,15.0,15.0
16,Duelist League Series 1 participation cards,4,4.0,4.0
17,Yu-Gi-Oh! The Duelists of the Roses promotional cards,6,6.0,3.0
18,Labyrinth of Nightmare,315,328.0,105.0
19,Tournament Pack: 3rd Season,20,20.0,20.0

### Cardset Count Investigation

- `cardsets.num_of_cards` does not always represent the number of unique cards.
- `cards_cardsets` may contain multiple rows for the same `card_id` within a set.
- Example: Legend of Blue Eyes White Dragon
  - `num_of_cards`: 355
  - `cards_cardsets` records: 358
  - Unique `card_id`s: 126
- For YGO Insight, unique card counts should be calculated using `card_id.nunique()`.
- Preserve `num_of_cards` as source metadata rather than replacing or deleting it.

# Phase 3a: Gameplay Feature Engineering

In [235]:
new_cards.columns

Index(['id', 'name', 'type', 'desc', 'atk', 'def', 'level', 'race',
       'attribute', 'scale', 'archetype', 'linkval', 'linkmarkers',
       'image_url', 'image_url_small', 'ban_tcg', 'ban_ocg', 'ban_goat',
       'views', 'upvotes', 'downvotes', 'formats', 'treated_as', 'tcg_date',
       'ocg_date', 'has_effect', 'release_year'],
      dtype='object')

In [236]:
new_cards["special_summon"] = new_cards["desc"].str.contains("Special Summon", case=False, na=False)

In [237]:
new_cards["can_search"] = new_cards["desc"].str.contains("from your Deck to your hand")
new_cards["can_search"].value_counts()

can_search
False    11970
True      1206
Name: count, dtype: int64

In [238]:
new_cards.loc[
    new_cards["can_search"],
    ["name", "desc"]
].sample(10)

,name,desc
5017,Goddess Verdande's Guidance,"When this card is activated: If all monsters you control are ""Valkyrie"" monsters (min. 1), you can add 1 ""Goddess Urd's Verdict"" from your Deck to your hand. Once per turn: You can declare 1 type of card (Monster, Spell, or Trap); reveal the top card of your opponent's Deck and if it was the declared type, they Set it to their field. Otherwise, they add it to their hand. You can only activate 1 ""Goddess Verdande's Guidance"" per turn."
5212,Graydle Impact,"You can target 1 other ""Graydle"" card you control and 1 card your opponent controls; destroy them. During your End Phase: You can add 1 ""Graydle"" card from your Deck to your hand. You can only use 1 ""Graydle Impact"" effect per turn, and only once that turn."
9540,Rescue-ACE Air Lifter,"If this card is Normal or Special Summoned: You can add 1 ""Rescue-ACE"" Spell from your Deck to your hand. When your opponent activates a monster effect on the field (Quick Effect): You can Tribute this card from your hand or face-up field; Special Summon 1 ""Rescue-ACE"" monster from your hand, except ""Rescue-ACE Air Lifter"". You can only use each effect of ""Rescue-ACE Air Lifter"" once per turn."
8636,Performapal Gentrude,"[ Pendulum Effect ] \nIf ""Performapal Ladyange"" is in your other Pendulum Zone and you control no monsters, or only Pendulum Monsters: You can add 1 ""Odd-Eyes"" card from your Deck to your hand. You can only use this effect of ""Performapal Gentrude"" once per turn.\n[ Monster Effect ] \nIf this card is destroyed: You can place 1 ""Performapal"" Pendulum Monster from your Deck in your Pendulum Zone, except ""Performapal Gentrude"". If this card is face-up in your Extra Deck: You can discard 1 Pendulum Monster; add this card to your hand, then you can return 1 ""Performapal"" or ""Odd-Eyes"" card from your Pendulum Zone to the hand. You can only use 1 ""Performapal Gentrude"" effect per turn, and only once that turn."
49,Abomination's Prison,"Add 1 ""Unchained"" card from your Deck to your hand. If this Set card is destroyed by card effect: You can Special Summon 1 ""Unchained"" monster from your Deck. You can only use each effect of ""Abomination's Prison"" once per turn."
5241,Green Gadget,"When this card is Normal or Special Summoned: You can add 1 ""Red Gadget"" from your Deck to your hand."
12768,Where Arf Thou?,"If you control a face-up Level 1 monster: Add 1 Level 1 monster from your Deck to your hand. During the End Phase of this turn, take 2000 damage if you did not Normal Summon the added monster, or a card with the same name, after activating this card."
8952,Predaplant Darlingtonia Cobra,"If this card is Special Summoned by the effect of a ""Predaplant"" monster: You can add 1 ""Polymerization"" Spell Card or ""Fusion"" Spell Card from your Deck to your hand. You can only use this effect of ""Predaplant Darlingtonia Cobra"" once per Duel."
7971,Nightmare Pain,"During your Main Phase: You can destroy 1 DARK monster in your hand or face-up field, and if you do, add 1 ""Yubel"", or 1 card that mentions it, from your Deck to your hand, except ""Nightmare Pain"". You can only use this effect of ""Nightmare Pain"" once per turn. While you control a ""Yubel"" monster, your opponent's monsters that can attack must attack ""Yubel"" monsters. Your opponent takes any battle damage you would have taken from battles involving your ""Yubel"" monsters."
7452,"Mikazukinoyaiba, the Moon Fang Dragon","During the End Phase, if this card is in your hand or GY: You can Special Summon it, but place it on the bottom of the Deck when it leaves the field. You can discard 1 card; add 1 Level 7 DARK Dragon monster from your Deck to your hand. You can only use each effect of ""Mikazukinoyaiba, the Moon Fang Dragon"" once per turn."

In [ ]:
# Initial draw-effect detection; refined later to capture more wording patterns
new_cards["can_draw"] = new_cards["desc"].str.contains(r"draw \d+ cards?", case=False, na=False, regex=True)
new_cards["can_draw"].value_counts()

can_draw
False    12531
True       645
Name: count, dtype: int64

In [240]:
new_cards.loc[
    new_cards["can_draw"],
    ["name", "desc"]
].sample(10)

,name,desc
4267,Flowerbot,"If this card is sent to the Graveyard: Draw 1 card, then place 1 card from your hand on the top of the Deck."
4224,Flick Clown,"If you control at least 2 other Cyberse monsters and have no cards in your hand: You can pay 1000 LP; draw 1 card. You can only use this effect of ""Flick Clown"" once per turn."
248,Ally of Justice Omni-Weapon,"When this card destroys a LIGHT monster by battle and sends it to the Graveyard, draw 1 card. If that card is a Level 4 or lower DARK monster, you can reveal that card to Special Summon it."
2514,Danger! Bigfoot!,"You can reveal this card in your hand; your opponent randomly chooses 1 card from your entire hand, then you discard the chosen card. Then, if the discarded card was not ""Danger! Bigfoot!"", Special Summon 1 ""Danger! Bigfoot!"" from your hand, and if you do, draw 1 card. If this card is discarded: You can target 1 face-up card your opponent controls; destroy it. You can only use this effect of ""Danger! Bigfoot!"" once per turn."
1881,Clear Effector,If this card is sent to the Graveyard as a Synchro Material: Draw 1 card. A Synchro Monster that used this card as a Synchro Material cannot be destroyed by card effects.
1398,Branded Regained,"If a LIGHT or DARK monster(s) is banished (except during the Damage Step): You can target 1 of those monsters; place that monster on the bottom of the Deck, and if you do, draw 1 card. You can only use this effect of ""Branded Regained"" once per turn. Once per turn, if your opponent Normal or Special Summons a monster (except during the Damage Step): You can target 1 ""Bystial"" monster in your GY; Special Summon it. You can only activate this effect of ""Branded Regained"" once per Chain."
5451,Heavy Slump,"If your opponent has 8 or more cards in their hand: They shuffle their entire hand into the Deck, then draw 2 cards."
2842,Desperado Barrel Dragon,"If a face-up DARK Machine monster(s) you control is destroyed by battle or card effect: You can Special Summon this card from your hand. Once per turn, during the Battle Phase (Quick Effect): You can toss a coin 3 times; destroy face-up monsters on the field, up to the number of heads, then if the result was 3 heads, draw 1 card. This card cannot attack the turn this effect is activated. If this card is sent to the GY: You can add 1 Level 7 or lower monster that has a coin tossing effect, from your Deck to your hand."
7614,Monster Slots,"Target 1 face-up monster you control and 1 monster in your Graveyard with the same Level; banish the target from the Graveyard, then draw 1 card and reveal it, then if the card you drew is a monster with the same Level as the monster on the field, Special Summon it."
5998,Ivy Shackles,All face-up monsters your opponent controls become Plant-Type during your turns only. If this face-up card you control is destroyed and sent to your Graveyard by an opponent's card effect: Draw 1 card.

In [241]:
new_cards["can_negate"] = new_cards["desc"].str.contains("negate", case=False,na=False)
new_cards["can_negate"].value_counts()

can_negate
False    11799
True      1377
Name: count, dtype: int64

In [242]:
new_cards.loc[
    new_cards["can_negate"],
    ["name", "desc"]
].sample(10)

,name,desc
11996,Tri-Brigade Airborne Assault,"Target 1 Beast, Beast-Warrior, or Winged Beast monster you control; Special Summon 1 Beast, Beast-Warrior, or Winged Beast monster from your Deck, in Defense Position, with a different Type and with ATK less than or equal to that monster, but its effects are negated until the end of this turn, also you cannot Special Summon monsters from the Extra Deck for the rest of this turn, except Link Monsters. You can only activate 1 ""Tri-Brigade Airborne Assault"" per turn."
6087,Junk Giant,"If your opponent controls a Level 5 or higher monster, you can Special Summon this card (from your hand). A Synchro Summon using this card as a Material cannot be negated. If a player Synchro Summons using this card as a Material, the other player cannot activate cards or effects when that monster is Synchro Summoned."
2460,D/D/D Headhunt,"If you control a ""D/D/D"" monster: Target 1 face-up monster your opponent controls; take control of it until the End Phase of the next turn, but its effects are negated, it cannot declare an attack, also if it is a monster Special Summoned from the Extra Deck, it is also treated as a ""D/D/D"" monster. You can only activate 1 ""D/D/D Headhunt"" per turn."
9446,Red-Eyes Dark Dragoon,"""Dark Magician"" + ""Red-Eyes Black Dragon"" or 1 Dragon Effect Monster\r\nCannot be destroyed by card effects. Neither player can target this card with card effects. During your Main Phase: You can destroy 1 monster your opponent controls, and if you do, inflict damage to your opponent equal to that monster's original ATK. You can use this effect a number of times per turn up to the number of Normal Monsters used as Fusion Material for this card. Once per turn, when a card or effect is activated (Quick Effect): You can discard 1 card; negate the activation, and if you do, destroy that card, and if you do that, this card gains 1000 ATK."
5238,Greedy Venom Fusion Dragon,"1 ""Predaplant"" monster + 1 DARK monster whose original Level is 8 or higher\r\nMust first be Fusion Summoned. Once per turn: You can target 1 face-up monster on the field; until the end of this turn, change that target's ATK to 0, also that target has its effects negated. If this card is destroyed and sent to the Graveyard: Destroy as many monsters on the field as possible, then you can banish 1 Level 8 or higher DARK monster from your Graveyard and Special Summon this card from the Graveyard."
746,Assault Revival,"Remove from play 1 ""Assault Mode Activate"" from your Graveyard. Destroy all monsters you control and Special Summon 1 ""/Assault Mode"" monster from your Graveyard, ignoring its Summoning conditions. Its effect(s) is negated, and it cannot be Tributed. If it is removed from the field, remove it from play."
865,Baelgrill de Nouvelles,"You can Ritual Summon this card with a ""Recipe"" card. If this card is Special Summoned: You can negate the effects of all face-up cards your opponent currently controls (until the end of this turn), then, if this card was Special Summoned by the effect of a ""Nouvelles"" monster, you can Tribute as many monsters your opponent controls as possible. (Quick Effect): You can target 1 Attack Position monster your opponent controls; Tribute it, and if you do, Special Summon 1 ""Hungry Burger"" from your hand or Deck. You can only use each effect of ""Baelgrill de Nouvelles"" once per turn."
1227,Blade Knight,"Gains 400 ATK while you have 1 or less cards in your hand. If you control no other monsters, the effects of Flip monsters destroyed by battle with this card are negated."
13068,Xyz Dimension Splash,"If this Set card is banished: You can Special Summon 2 Level 8 WATER monsters from your Deck. Their effects are negated, also they cannot declare an attack or be Tributed."
13051,Xiangke Magician,"[ Pendulum Effect ] \nOnce per turn: You can target 1 face-up Xyz Monster you control; this turn, you can use it as an Xyz Material for an Xyz Summon using its Rank as if it were a Level (even if this card leaves the field).\n[ Monster Effect ] \nOnce per turn, during either player's turn: You can target 1 LIGHT monster on the field; that face-up monster has its effects negated until the end of this turn."

In [243]:
new_cards["can_destroy"] = new_cards["desc"].str.contains("destroy ", case=False, na=False)
new_cards["can_destroy"].value_counts()

can_destroy
False    10643
True      2533
Name: count, dtype: int64

In [244]:
new_cards.loc[
    new_cards["can_destroy"],
    ["name", "desc"]
].sample(10)

,name,desc
2858,Destiny HERO - Celestial,"When this card declares an attack: You can target 1 face-up Spell your opponent controls; destroy it, and if you do, inflict 500 damage to your opponent. While you have no cards in your hand, except the turn this card was sent to the GY: You can banish this card and 1 ""Destiny HERO"" monster from your GY; draw 2 cards. You can only use this effect of ""Destiny HERO - Celestial"" once per turn."
3403,Dual Avatar - Empowered Mitsu-Jaku,"""Dual Avatar Feet - Kokoku"" + 2 ""Dual Avatar"" monsters\r\nThe first time each ""Dual Avatar"" Fusion Monster you control would be destroyed by battle each turn, it is not destroyed. Once per turn, during your Main Phase: You can return all Spells and Traps your opponent controls to the hand. When a monster effect is activated on your opponent's field while you control 2 or more Fusion Monsters (Quick Effect): You can destroy that monster. You can only use this effect of ""Dual Avatar - Empowered Mitsu-Jaku"" once per turn."
9980,Savage Colosseum,"If a monster attacks, at the end of the Damage Step: Its controller gains 300 LP. All monsters must attack, if able. During each End Phase: Destroy all face-up Attack Position monsters the turn player controls, that did not declare an attack."
7164,Masterking Archfiend,"2 Fiend monsters\nOnce per turn, during your Standby Phase, pay 500 LP or destroy this card. Once per Chain, if you pay LP (except during the Damage Step): You can send 1 Fiend monster from your Deck to the GY with ATK or DEF equal to the amount paid. Once per Chain, if a Fiend monster(s) is sent to your GY (except during the Damage Step): You can roll a six-sided die, then apply this effect on 1 of those monsters based on the result.\n● 1: Add it to your hand. ● 2, 3, 4, 5: Shuffle into the Deck. ● 6: Special Summon it."
10955,Stronghold the Hidden Fortress,"Special Summon this card as an Effect Monster (Machine/EARTH/Level 4/ATK 0/DEF 2000) with the following effects (this card is also still a Trap).\r\n● Gains 1000 ATK for each ""Shining Sarcophagus"", and monster that mentions it, that you control.\r\n● Once per turn, when an opponent's monster declares an attack, while you control ""Shining Sarcophagus"": You can destroy that monster."
12106,"True King Lithosagym, the Disaster","If this card is in your hand: You can destroy 2 other monsters in your hand and/or face-up field, including an EARTH monster, and if you do, Special Summon this card, and if you do that, and both destroyed monsters were EARTH, you can also look at your opponent's Extra Deck and banish up to 3 monsters from it with different names. If this card is destroyed by card effect: You can Special Summon 1 non-EARTH Wyrm monster from your GY. You can only use each effect of ""True King Lithosagym, the Disaster"" once per turn."
1413,Break! Draw!,Equip only to a Machine monster. If the equipped monster destroys an opponent's monster by battle and sends it to the GY: Draw 1 card. Destroy this card during your 3rd End Phase after activation.
9517,Reptilianne Hydra,"1 ""Reptilianne"" Tuner + 1 or more non-Tuner monsters\r\nWhen this card is Synchro Summoned, destroy all face-up monsters with 0 ATK that your opponent controls, and draw 1 card for each monster destroyed."
3353,Dream Absorber,"If your opponent activates a monster effect in the hand, GY, or banishment (except during the Damage Step): You can Special Summon this card from your GY (if it was there when the effect was activated) or hand (even if not), but destroy it during the End Phase. You can only use this effect of ""Dream Absorber"" once per turn. Each time your opponent activates a monster effect, this card gains 1000 ATK immediately after it resolves."
12978,Worldsea Dragon Zealantis,"1+ Effect Monsters\r\nYou can only control 1 ""Worldsea Dragon Zealantis"". You can only use each of the following effects of ""Worldsea Dragon Zealantis"" once per turn. During your Main Phase: You can banish all monsters on the field, then Special Summon as many monsters as possible that were banished by this effect, to their owners' fields, face-up, or in face-down Defense Position. During the Battle Phase (Quick Effect): You can destroy cards on the field up to the number of co-linked monsters on the field."

In [245]:
new_cards[new_cards["name"]=="Number 39: Utopia"][["can_destroy", "name", "desc"]]

,can_destroy,name,desc
8113,True,Number 39: Utopia,"2 Level 4 monsters\r\nWhen a monster declares an attack: You can detach 1 material from this card; negate the attack. If this card is targeted for an attack, while it has no material: Destroy this card."

In [246]:
new_cards["uses_gy"] = (new_cards["desc"].str.contains("GY", case=False, na=False)| new_cards["desc"].str.contains("Graveyard", case=False, na=False))
new_cards["uses_gy"].value_counts()

uses_gy
False    6857
True     6319
Name: count, dtype: int64

In [247]:
new_cards.loc[
    new_cards["uses_gy"],
    ["name", "desc"]
].sample(10)

,name,desc
11190,"Sweet Dreams, Nemleria","Add 1 ""Nemleria"" monster from your Deck to your hand, then, if you have a face-up ""Dreaming Nemleria"" in your Extra Deck, your opponent cannot activate cards or effects when a ""Nemleria"" monster(s) is Normal or Special Summoned this turn. You can place this card from your GY on the bottom of the Deck, then target 1 ""Dreaming Nemleria"" you control; add it to the Extra Deck face-up. You can only activate 1 ""Sweet Dreams, Nemleria"" per turn."
11382,Tearlaments Kashtira,"During the Main Phase (Quick Effect): You can Special Summon this card from your hand, and if you do, banish 1 ""Kashtira"" or ""Tearlaments"" card from your hand or GY. If this card is Normal or Special Summoned: You can send the top 3 cards of either player's Deck to the GY. If this card is sent to the GY by card effect: You can send the top 2 cards of your Deck to the GY. You can only use each effect of ""Tearlaments Kashtira"" once per turn."
6134,Kagero the Cannon Ninja,"If this card is Normal Summoned, Special Summoned, or flipped face-up: You can Special Summon 1 ""Ninja"" monster from your hand or GY in face-down Defense Position, except ""Kagero the Cannon Ninja"". When your opponent activates a card or effect that targets exactly 1 ""Ninja"" card or exactly 1 face-down Defense Position monster you control, while this card is in your GY (Quick Effect): You can Special Summon this card in face-down Defense Position, and if you do, return that targeted card to the hand. You can only use each effect of ""Kagero the Cannon Ninja"" once per turn."
5786,Imprudent Intrusion,Your LP must be lower than your opponent's to activate and to resolve this effect.\r\nActivate 1 of these effects;\r\n● Destroy 1 monster your opponent controls with ATK less than or equal to the difference in LP.\r\n● Special Summon 1 monster from your GY with ATK less than or equal to the difference in LP.
7859,Necroquip Princess,"1 monster equipped with a Monster Card + 1 Fiend Monster Card\r\nMust be Special Summoned (from your Extra Deck) by sending the above cards from your hand and/or field to the GY. You can only control 1 ""Necroquip Princess"". If a monster(s) is sent from the hand to the GY to activate a card or effect: You can activate 1 of these effects;\r\n● Equip 1 of those monsters to this card as an Equip Spell that gives it 500 ATK.\r\n● Draw 1 card.\r\nYou can only use this effect of ""Necroquip Princess"" once per turn."
4535,Galactikuriboh,"(This card is always treated as a ""Galaxy"" card.)\r\nWhen an opponent's monster declares an attack: You can discard this card; Special Summon 1 ""Galaxy-Eyes Photon Dragon"" from your hand or Deck, then change the attack target to it, then you can attach this card from the GY to 1 Xyz Monster on the field as material. If a ""Photon"" or ""Galaxy"" monster(s) you control would be destroyed by battle or an opponent's card effect, you can banish this card from your GY instead."
9515,Reptilianne Gardna,"When this card you control is destroyed and sent to the Graveyard, add 1 ""Reptilianne"" monster from your Deck to your hand."
3064,Divine Arsenal AA-ZEUS - Sky Thunder,"2 Level 12 monsters\r\nOnce per turn, if an Xyz Monster battled this turn, you can also Xyz Summon ""Divine Arsenal AA-ZEUS - Sky Thunder"" by using 1 Xyz Monster you control as material. (Transfer its materials to this card.) (Quick Effect): You can detach 2 materials from this card; send all other cards from the field to the GY. Once per turn, if another card(s) you control is destroyed by battle or an opponent's card effect: You can attach 1 card from your hand, Deck, or Extra Deck to this card as material."
1803,Chimeratech Megafleet Dragon,"1 ""Cyber Dragon"" monster + 1+ monsters in the Extra Monster Zone\r\nCannot be used as Fusion Material. Must first be Special Summoned (from your Extra Deck) by sending the above cards from either field to the GY. (You do not use ""Polymerization"".) The original ATK of this card becomes 1200 x the number of Fusion Materials used for its Special Summon."
12772,Whirlwind of Gusto,"If you control no monsters: Target 2 ""Gusto"" monsters in your Graveyard; shuffle both targets into the Deck, then Special Summon 1 ""Gusto"" monster with 1000 or less DEF from your Deck."

In [248]:
new_cards["can_banish"] = new_cards["desc"].str.contains("banish", case=False, na=False)
new_cards["can_banish"].value_counts()

can_banish
False    10775
True      2401
Name: count, dtype: int64

In [249]:
new_cards.loc[
    new_cards["can_banish"],
    ["name", "desc"]
].sample(10)

,name,desc
1238,"Blaster, Dragon Ruler of Infernos","If this card is in your hand or Graveyard: You can banish a total of 2 FIRE and/or Dragon-Type monsters from your hand and/or Graveyard, except this card; Special Summon this card. During your opponent's End Phase, if this card was Special Summoned: Return it to the hand. You can discard this card and 1 FIRE monster to the Graveyard, then target 1 card on the field; destroy that target. If this card is banished: You can add 1 FIRE Dragon-Type monster from your Deck to your hand. You can only use 1 ""Blaster, Dragon Ruler of Infernos"" effect per turn, and only once that turn."
6070,Jungle Dweller,"Cannot be Normal Summoned/Set. Must be Special Summoned by card effect. While there are 2 cards in the Field Zones, your opponent cannot target this card with card effects. You can only use each of the following effects of ""Jungle Dweller"" once per turn. You can banish 1 LIGHT or DARK monster from your GY; Special Summon this card from your hand. If this card in its owner's possession is destroyed by an opponent's card: You can shuffle up to 2 of your Field Spells from your GY or banishment into the Deck, then you can destroy up to that many cards your opponent controls."
2200,Crystron Prasiortle,"You can target 1 face-up card you control; you cannot Special Summon monsters from the Extra Deck for the rest of this turn, except Machine-Type Synchro Monsters, also, destroy that card, and if you do, Special Summon 1 ""Crystron"" Tuner from your Deck. You can banish this card from your Graveyard; Special Summon 1 ""Crystron"" monster from your hand. You can only use 1 ""Crystron Prasiortle"" effect per turn, and only once that turn."
11756,Thunder Dragonduo,"Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand) by banishing 1 LIGHT and 1 DARK monster from your GY. Once per turn, if a monster effect is activated in the hand: This card gains 300 ATK until the end of this turn. When this card destroys an opponent's monster by battle: You can banish 1 card from your GY; add 1 Thunder monster from your Deck to your hand. Once per turn, during your opponent's End Phase: You can target 1 of your banished cards; place it on the top or bottom of your Deck."
8485,Paleozoic Canadia,"Target 1 face-up monster your opponent controls; change it to face-down Defense Position. Once per Chain, when a Trap Card is activated while this card is in your GY: You can Special Summon this card as a Normal Monster (Aqua/WATER/Level 2/ATK 1200/DEF 0). (This card is NOT treated as a Trap.) If Summoned this way, this card is unaffected by monster effects, also banish it when it leaves the field."
11414,Tenchi Kaimei,"(This card is always treated as a ""Ninjitsu Art"" card.)\r\nWhen a ""Ninja"" monster you control inflicts battle damage to your opponent: You can target 1 card your opponent controls; destroy it. If this face-up card in its owner's Field Zone has left the field because of an opponent's effect, and is now in the GY or banished: You can target any number of ""Ninja"" monsters with different names in your GY; Special Summon them in face-down Defense Position."
7477,Mimighoul Room,"Special Summon 1 ""Mimighoul"" monster from your hand or Deck to your field, or in face-down Defense Position to your opponent's field, then you can change 1 face-up monster on the field to face-down Defense Position. You can banish this card from your GY, then target any number of ""Mimighoul"" cards you control; return them to the hand. You can only use 1 ""Mimighoul Room"" effect per turn, and only once that turn."
13246,Zombie Power Struggle,"Target 1 Zombie monster on the field; until the end of this turn, it gains 1000 ATK or loses 1000 ATK. During your Main Phase, if this card is in your GY: You can shuffle 1 of your banished Zombie monsters into the Deck, and if you do, Set this card, but banish it when it leaves the field. You can only use this effect of ""Zombie Power Struggle"" once per turn."
685,Aromalilith Magnolia,"1 ""Aroma"" monster + 1 Plant monster\r\nWhile your LP are higher than your opponent's, Plant monsters you control cannot be destroyed by your opponent's card effects. Once per turn: You can pay 2000 LP; banish cards on the field equal to the number of ""Humid Winds"", ""Dried Winds"", and ""Blessed Winds"" you control. Once per turn, if you gain LP, even during the Damage Step: You can make all Plant monsters you currently control gain ATK equal to the LP gained, until the end of this turn."
7912,Neo Flamvell Lady,"(Quick Effect): You can send 1 FIRE monster from your hand to the GY, then target 1 card in your opponent's GY; banish that card. If a card is banished from your opponent's GY, while you control this monster (except during the Damage Step): You can send 1 FIRE monster with 200 or less DEF from your Deck to the GY, except ""Neo Flamvell Lady"". You can only use each effect of ""Neo Flamvell Lady"" once per turn."

In [250]:
new_cards["quick_effect"] = new_cards["desc"].str.contains("(Quick Effect)", case=False, na=False, regex=False)
new_cards["quick_effect"].value_counts()

quick_effect
False    12339
True       837
Name: count, dtype: int64

In [251]:
new_cards.loc[new_cards["quick_effect"], ["name", "desc"]].sample(10)

,name,desc
10948,Strike Ninja,"(Quick Effect): You can banish 2 DARK monsters from your GY; banish this face-up card until the End Phase. You can only use this effect of ""Strike Ninja"" once per turn."
2144,Crusadia Equimax,"2+ Effect Monsters, including a Link Monster\r\nGains ATK equal to the combined original ATK of all monsters this card points to. Monsters this card points to cannot attack. Once per turn (Quick Effect): You can Tribute 1 ""Crusadia"" or ""World Legacy"" monster this card points to, then target 1 face-up card your opponent controls; negate its effects until the end of this turn."
8351,"Oneiros, the Dream Mirror Tormentor","2 ""Dream Mirror"" monsters with different Attributes\r\nWhile face-up on the field, this card is also LIGHT-Attribute. You can only use each of the following effects of ""Oneiros, the Dream Mirror Tormentor"" once per turn.\r\n● When a monster effect is activated while ""Dream Mirror of Terror"" is in a Field Zone (Quick Effect): You can negate that effect.\r\n● If ""Dream Mirror of Joy"" is in a Field Zone (Quick Effect): You can Tribute this card; Special Summon 1 ""Oneiros, the Dream Mirror Erlking"" from your Extra Deck in Defense Position."
12445,Vanquish Soul Pluton HG,"During your opponent's turn, if you control no monsters, or only ""Vanquish Soul"" monsters, in your Main Monster Zone (Quick Effect): You can Special Summon this card from your hand. (Quick Effect): You can activate 1 of these effects, by revealing monster(s) in your hand with the listed Attribute(s);\r\n● FIRE: This card gains 3000 DEF until the end of this turn.\r\n● DARK & EARTH: This card gains 3000 ATK until the end of this turn.\r\nYou can only use each effect of ""Vanquish Soul Pluton HG"" once per turn, and cannot activate more than 1 in the same Chain."
3830,Evil★Twin Ki-sikil,"2 monsters, including a ""Ki-sikil"" monster\r\nIf this card is Special Summoned and you control a ""Lil-la"" monster: You can draw 1 card. During the Main Phase, if you do not control a ""Lil-la"" monster (Quick Effect): You can Special Summon 1 ""Lil-la"" monster from your GY, also you cannot Special Summon monsters from the Extra Deck for the rest of this turn, except Fiend monsters. You can only use each effect of ""Evil★Twin Ki-sikil"" once per turn."
636,Armed Neos,"""Elemental HERO Neos"" + 1 ""Armed Dragon"" monster\r\nMust be Fusion Summoned. If this card is Special Summoned: You can choose 1 Dragon monster in your GY and destroy all monsters your opponent controls with an equal or lower Level than it. When this card destroys a monster by battle: You can make this card gain the following effect.\r\n● During the Main Phase (Quick Effect): You can Tribute this card; Special Summon 1 ""Elemental HERO"" Fusion Monster from your Extra Deck, ignoring its Summoning conditions."
1358,Borrelguard Dragon,"3+ Effect Monsters\r\nCannot be destroyed by card effects. Once per turn: You can send 1 card from your Spell & Trap Zone to the GY; Special Summon from either GY to your field, 1 monster that was destroyed and sent there this turn, but negate its effects. Once per turn (Quick Effect): You can target 1 monster on the field; change it to face-up Defense Position. Your opponent cannot activate cards or effects in response to this effect's activation."
8238,Numeron Wall,"If you control no cards, except ""Numeron Wall(s)"" (Quick Effect): You can send this card from your hand or field to the GY; activate 1 ""Numeron Network"" directly from your hand or Deck. You can only use this effect of ""Numeron Wall"" once per turn. When you take battle damage: You can Special Summon this card from your hand, and if you do, end the Battle Phase after the Damage Step."
7463,Millennium-Eyes Illusionist,"(Quick Effect): You can discard this card, then target 1 Effect Monster your opponent controls; equip that target to an ""Eyes Restrict"" Fusion Monster or ""Relinquished"" you control, as if it were equipped by that monster's effect. If an ""Eyes Restrict"" Fusion Monster(s) or a ""Relinquished"" is Special Summoned: Add this card from your GY to your hand (this is not optional). You can only use each effect of ""Millennium-Eyes Illusionist"" once per turn."
3488,Earthbound Servant Geo Gremlin,"1 DARK Tuner + 1+ non-Tuner monsters\r\nDuring the Main Phase (Quick Effect): You can target 1 face-up monster your opponent controls; your opponent chooses 1 of these effects for you to apply.\r\n● Destroy that monster. ● Gain LP equal to that monster's ATK.\r\nDuring the Battle Phase (Quick Effect): You can Fusion Summon 1 ""Earthbound"" Fusion Monster from your Extra Deck, by banishing its materials from your hand, field, and/or GY. You can only use each effect of ""Earthbound Servant Geo Gremlin"" once per turn."

In [252]:
new_cards["from_your_hand"] = new_cards["desc"].str.contains("from your hand", case=False, na=False)
new_cards["from_your_hand"].value_counts()

from_your_hand
False    10156
True      3020
Name: count, dtype: int64

In [253]:
new_cards.loc[
    new_cards["from_your_hand"],
    ["name", "desc"]
].sample(10)

,name,desc
7966,Nightmare Apprentice,"You can Special Summon this card (from your hand) by discarding 1 card. You can only Special Summon ""Nightmare Apprentice"" once per turn this way. If this card battles a monster, neither can be destroyed by that battle. If this card is Normal or Special Summoned: You can add 1 Illusion monster from your Deck to your hand, except ""Nightmare Apprentice"". You can only use this effect of ""Nightmare Apprentice"" once per turn."
5608,Honest,"During your Main Phase: You can return this face-up card from the field to the hand. During the Damage Step, when a LIGHT monster you control battles (Quick Effect): You can send this card from your hand to the GY; that monster gains ATK equal to the ATK of the opponent's monster it is battling, until the end of this turn."
596,Archfiend's Promotion,"Once per turn, during your Main Phase, if you control ""Vilepawn Archfiend"" and your opponent controls no card in its same column, you can Tribute it to Special Summon 1 Level 8 or lower ""Archfiend"" monster from your hand or Deck that has ""Queen"", ""Bishop"" , ""Rook"", or ""Knight"" in its name."
3674,Emblema Salvation,"Banish 1 face-up ""Centur-Ion"" Monster Card from your Spell & Trap Zone, then target 1 card your opponent controls; banish it. If this Set card in its owner's control is destroyed or banished by an opponent's activated effect: You can place 2 ""Centur-Ion"" monsters with different names from your hand, Deck, GY, and/or banishment in your Spell & Trap Zone as face-up Continuous Traps. You can only activate 1 ""Emblema Salvation"" per turn."
4901,Gishki Nekromirror,"This card can be used to Ritual Summon any ""Gishki"" Ritual Monster. You must also Tribute monsters from your hand or field, whose total Levels exactly equal the Level of the Ritual Monster you Ritual Summon, OR Tribute 1 face-up monster your opponent controls. If you Ritual Summon using this card, you lose LP equal to the original ATK of the Ritual Summoned monster. If this card is in your GY: You can target 1 ""Gishki"" monster in your GY; place that card on top of the Deck, and if you do, place this card on the bottom of the Deck."
6916,Magicians of Bonds and Unity,"Cannot be Normal Summoned/Set. Must be Special Summoned (from your hand) by having 25 or more cards in your GY. While your opponent has 25 or more cards in their GY, this card gains 2500 ATK/DEF."
9805,S-Force Orrafist,"Your opponent cannot target any of their monsters in the same column as one of your ""S-Force"" monsters with card effects. When a monster your opponent controls activates its effect (Quick Effect): You can banish 1 ""S-Force"" card from your hand; destroy that monster. You can only use this effect of ""S-Force Orrafist"" once per turn."
12741,Wattrain,"Add ""Watt"" cards with different names from your Deck to your hand, except ""Wattrain"", up to the number of Thunder monsters you control with different names. During your Main Phase, except the turn this card was sent to the GY: You can banish this card from your GY; Special Summon as many ""Watt"" monsters as possible with different names from your hand. You can only use each effect of ""Wattrain"" once per turn."
6645,Litmus Doom Ritual,"This card is used to Ritual Summon ""Litmus Doom Swordsman"". You must also Tribute monsters from your hand or field, whose total Levels equal 8 or more. If this card is in the GY: You can target 1 ""Litmus Doom Swordsman"" in your GY; shuffle both it and this card from the GY into the Deck, then draw 1 card. You can only use this effect of ""Litmus Doom Ritual"" once per turn."
2158,Cry Havoc!,You can remove from play 1 monster from your Graveyard to Normal Summon or Set 1 Normal Monster from your hand. You can only activate this effect during your Main Phase.

In [254]:
new_cards[new_cards["name"]=="Rainbow Neos"][["name", "desc"]]

,name,desc
9300,Rainbow Neos,"""Elemental HERO Neos"" + 1 ""Ultimate Crystal"" monster\nMust be Fusion Summoned with the above Fusion Material Monsters and cannot be Special Summoned by other ways. Once per turn: You can activate 1 of these effects. ● Send 1 monster you control to the Graveyard; shuffle all monsters your opponent controls into the Deck. ● Send 1 Spell/Trap Card you control to the Graveyard; shuffle all Spell and Trap Cards your opponent controls into the Deck. ● Send 1 card from the top of your Deck to the Graveyard; shuffle all cards in your opponent's Graveyard into the Deck."

In [ ]:
# Identify descriptions containing card-protection mechanics
new_cards["protection"] = (
    new_cards["desc"].str.contains("cannot be destroyed", case=False, na=False)
    |
    new_cards["desc"].str.contains("cannot be targeted", case=False, na=False)
    |
    new_cards["desc"].str.contains("cannot be banished", case=False, na=False)
    |
    new_cards["desc"].str.contains("unaffected", case=False, na=False)
)
new_cards["protection"].value_counts()

protection
False    12228
True       948
Name: count, dtype: int64

In [256]:
new_cards.loc[
    new_cards["protection"],
    ["name", "desc"]
].sample(10)

,name,desc
6840,Magic Gate of Miracles,"If you control 2 or more Spellcaster monsters: Change 1 Attack Position monster your opponent controls to Defense Position, then take control of it, and if you do, it cannot be destroyed by battle."
13230,Zexal Alliance,"If a face-up Xyz Monster(s) you control is destroyed by battle or an opponent's card effect: Pay LP so that you only have 10 left; Special Summon 1 ""Utopia"" monster from your GY, and if you do, take 1 card from your Deck and place it on top of your Deck. That Special Summoned monster's ATK becomes doubled, also it cannot be destroyed by battle, except by battle with a ""Number"" monster, nor by card effects."
11697,The Winged Dragon of Ra - Immortal Phoenix,"Cannot be Normal Summoned/Set. Must be Special Summoned by its own effect. If ""The Winged Dragon of Ra"" is sent from the field to your GY while this card is in your GY: Special Summon this card. Cards and effects cannot be activated in response to this effect's activation. This card is unaffected by other cards' effects. You can pay 1000 LP; send 1 monster on the field to the GY. Once per turn, during the End Phase: Send this card to the GY, and if you do, Special Summon 1 ""The Winged Dragon of Ra - Sphere Mode"" from your hand, Deck, or GY, ignoring its Summoning conditions."
5203,Gravity Controller,"1 non-Link Monster in an Extra Monster Zone\r\nCannot be used as Link Material the turn it is Link Summoned. This card in the Extra Monster Zone cannot be destroyed by battle with a monster in the Main Monster Zone. At the start of the Damage Step, if this card battles an opponent's monster in the Extra Monster Zone: You can return both that opponent's monster and this card to the Deck."
1778,Charm of Shabti,"During either player's turn: You can discard this card; until the End Phase, ""Gravekeeper's"" monsters you control cannot be destroyed by battle."
7295,Melffy Mommy,2+ Level 2 Beast monsters\r\nOnce per turn (Quick Effect): You can attach 1 Beast monster from your hand or face-up field to this card as material. This card gains effects based on the number of materials attached to it.\r\n● 3+: Cannot be destroyed by battle.\r\n● 4+: You take no damage from battles involving this card.\r\n● 5+: When an attack is declared involving this card and an Attack Position monster: You can inflict damage to your opponent equal to that Attack Position monster's ATK.
12681,War Rock Meteoragon,"Cannot be destroyed by an opponent's card effects. When an attack is declared involving this card and an opponent's monster: You can negate that opponent's monster's effects this turn, as well as the activated effects and effects on the field of monsters with its same original name. Once per turn, during a Battle Phase in which your EARTH Warrior monster battles (Quick Effect): You can make all ""War Rock"" monsters you currently control gain 200 ATK until the end of your opponent's turn, also this card can make up to 2 attacks on monsters during each Battle Phase this turn."
7216,Mecha Phantom Beast Raiten,"You can discard 1 card; Special Summon 1 ""Mecha Phantom Beast Token"" (Machine/WIND/Level 3/ATK 0/DEF 0), also you can only use ""Mecha Phantom Beast"" monsters as Fusion, Synchro, Xyz, or Link Material for a Summon, for the rest of this turn. This card's Level is increased by the total Levels of all ""Mecha Phantom Beast Tokens"" you control. While you control a Token, this card cannot be destroyed by battle or card effects."
6974,Majespecter Cat - Nekomata,"When this card is Normal or Special Summoned: You can add 1 ""Majespecter"" card from your Deck to your hand during the End Phase of this turn. You can only use this effect of ""Majespecter Cat - Nekomata"" once per turn. Cannot be targeted or destroyed by your opponent's card effects."
3089,Djinn Disserere of Rituals,"When you Ritual Summon a monster, you can banish this card from your GY as 1 of the monsters required for the Ritual Summon. The monster Ritual Summoned using this card is unaffected by Trap effects."

In [257]:
new_cards["atk_def_cards"] = (
    new_cards["desc"].str.contains("ATK", case=True, na=False)
    |
    new_cards["desc"].str.contains("DEF", case=True, na=False)
)
new_cards["atk_def_cards"].value_counts()

atk_def_cards
False    9790
True     3386
Name: count, dtype: int64

In [258]:
new_cards.loc[
    new_cards["atk_def_cards"],
    ["name", "desc"]
].sample(10)

,name,desc
1651,Cat Shark,"2 Level 2 monsters\nWhile this card has an Xyz Material attached that was originally WATER, it cannot be destroyed by battle. Once per turn, during either player's turn: You can detach 1 Xyz Material from this card, then target 1 Rank 4 or lower Xyz Monster you control; its ATK and DEF each become double its original ATK and DEF until the end of this turn."
2996,Dino-Sewing,"Cannot be destroyed by battle. If this card is targeted for an attack: This card gains 1000 ATK and DEF. If this card attacked, after damage calculation: The ATK and DEF gained from this effect returns to 0."
8032,Noble Knight Joan,"If this card attacks, it loses 300 ATK during the Damage Step only. If this card in your possession is destroyed by your opponent's card (either by battle or by card effect) and sent to your Graveyard: You can send 1 card from your hand to the Graveyard then target 1 Level 4 or lower Warrior-Type monster in your Graveyard; add that target to your hand."
10169,Shadow Ghoul,This card gains 100 ATK for each monster in your Graveyard.
12051,Trickstar Colchica,"1 non-Link ""Trickstar"" monster\r\nYou can only Special Summon ""Trickstar Colchica(s)"" once per turn. When a monster(s) is destroyed by battle involving your ""Trickstar"" monster while this card is in your GY: You can banish this card, then target 1 of those destroyed monsters; inflict damage to your opponent equal to its ATK. You can only use this effect of ""Trickstar Colchica"" once per turn."
2859,Destiny HERO - Dangerous,"1 ""Destiny HERO"" monster + 1 DARK Effect Monster\r\n(Quick Effect): You can discard 1 card; send 1 ""Destiny HERO"" monster from your hand or Deck to the GY, and if you do, ""Destiny HERO"" monsters you control gain 200 ATK for each ""Destiny HERO"" monster in your GY until the end of this turn. You can only use this effect of ""Destiny HERO - Dangerous"" once per turn."
137,Additional Mirror Level 7,"If a Level 7 monster(s) is Special Summoned to your field: Send 2 ""Additional Mirror Level 7"" from your hand and/or Deck to the GY, then target 1 of those monsters; Special Summon 2 monsters with the same name as that target from your Deck, then take damage equal to their combined original ATK, also, for the rest of this turn after this card resolves, you can only Special Summon from the Extra Deck once."
5950,Inzektor Ant,"Once per turn: You can equip 1 ""Inzektor"" monster from your hand or Graveyard to this card. While this card is equipped to a monster, that monster's Level is increased by 3, also it gains ATK and DEF equal to this card's ATK and DEF. If the equipped monster would be destroyed, you can destroy this Equip Card instead."
4506,Gagagarevenge,"Target 1 ""Gagaga"" monster in your Graveyard; Special Summon it and equip it with this card. When this card leaves the field, destroy the equipped monster. When this card is sent to the Graveyard because the equipped monster was used as an Xyz Material: All Xyz Monsters you currently control gain 300 ATK."
9762,Rubisapphirus the Jewel of Maximum Mohs,"2+ Level 9 monsters\r\nIf this card would be destroyed, you can detach 1 material from this card instead. This card gains effects based on its attached materials' Attributes.\r\n● FIRE: When this card declares an attack on a monster with higher ATK: You can make this card's ATK become doubled until the end of the Damage Step.\r\n● WATER: Once per opponent's turn (Quick Effect): You can target 1 card you control; negate any card or effect your opponent activates this turn that targets that card."

In [259]:
new_cards["piercing"] = (
    new_cards["desc"].str.contains(
        "piercing battle damage",
        case=False,
        na=False
    )
    |
    new_cards["desc"].str.contains(
        "inflict the difference as Battle Damage",
        case=False,
        na=False
    )
)
new_cards["piercing"].value_counts()

piercing
False    12998
True       178
Name: count, dtype: int64

In [260]:
new_cards.loc[
    new_cards["piercing"],
    ["name", "desc"]
].sample(10)

,name,desc
11932,Train Connection,"Must be equipped to an EARTH Machine-Type monster, by banishing 2 Level 10 or higher Machine-Type monsters from your Graveyard, and cannot be equipped by other ways. The equipped monster's ATK becomes double its original ATK, also if it attacks a Defense Position monster, inflict piercing battle damage to your opponent. Other monsters you control cannot attack."
3304,Dragunity Angusticlavii,"While this card is equipped with a Dragon-Type ""Dragunity"" monster, during battle between this attacking card and a Defense Position monster whose DEF is lower than the ATK of this monster, inflict the difference as Battle Damage to your opponent."
7316,Mementotlan Bone Party,"Destroy 1 ""Memento"" monster in your hand or face-up field, take 1 ""Memento"" monster from your Deck with a different name, and either add it to your hand or Special Summon it in Defense Position. During your Main Phase: You can banish this card from your GY, then target 1 ""Memento"" monster you control; if it attacks a Defense Position monster this turn, inflict piercing battle damage to your opponent. You can only use each effect of ""Mementotlan Bone Party"" once per turn."
11079,Super Vehicroid Jumbo Drill,"""Steamroid"" + ""Drillroid"" + ""Submarineroid""\nA Fusion Summon of this card can only be conducted with the above Fusion Material Monsters. During battle between this attacking card and a Defense Position monster whose DEF is lower than the ATK of this card, inflict the difference as Battle Damage to your opponent."
8252,Obliterate!!! Blaze,"One Level 10 or higher monster on the field with ""Exodia"" in its original name gains these effects.\r\n● You can pay half your LP; destroy as many cards in the Spell & Trap Zones as possible, then equip 5 ""Forbidden One"" monsters from your hand and/or Deck to this card as Equip Spells that each give it 2000 ATK, also you cannot activate other cards' effects for the rest of this turn.\r\n● If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent."
3934,F.A. Dawn Dragster,"1 Tuner + 1+ non-Tuner monsters\r\nGains ATK equal to its Level x 300. If this card attacks a Defense Position monster, inflict piercing battle damage. Each time a ""F.A."" Spell/Trap Card or effect is activated: You can increase this card's Level by 1. Once per turn, when your opponent activates a Spell/Trap Card or effect (Quick Effect): You can reduce this card's Level by 2, and if you do, negate the activation, and if you do that, destroy that card."
1840,Chronomaly Mud Golem,"If a ""Chronomaly"" monster you control attacks a Defense Position monster, inflict piercing battle damage to your opponent."
6404,Lancer Dragonute,"If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent."
6441,Laval Dual Slasher,"1 Tuner + 1 or more non-Tuner FIRE monsters\nThis card gains effects based on the number of ""Laval"" monsters in your Graveyard:\n● 2+: Once per turn, if this card attacks a Defense Position monster, it can attack once again in a row.\n● 3+: If this card attacks a Defense Position monster, inflict piercing Battle Damage to your opponent."
4011,Familiar-Possessed - Aussa,"You can Special Summon this card (from your hand or Deck) by sending 1 face-up ""Aussa the Earth Charmer"" and 1 face-up EARTH monster you control to the GY. If this card Special Summoned by its own effect attacks a Defense Position monster, inflict piercing battle damage."

In [ ]:
# Initial effect-damage detection, excluding references to battle damage
new_cards["burn"] = (
    new_cards["desc"].str.contains("inflict", case=False, na=False)
    &
    ~new_cards["desc"].str.contains("battle damage", case=False, na=False)
)

new_cards["burn"].value_counts()

burn
False    12541
True       635
Name: count, dtype: int64

In [262]:
new_cards.loc[
    new_cards["burn"],
    ["name", "desc"]
].sample(10)

,name,desc
7665,Morphtronic Rusty Engine,"Equip only to a ""Morphtronic"" monster. If the equipped monster is destroyed, inflict damage to each player equal to its original ATK."
896,Barrel Behind the Door,Activate only when a card's effect that would inflict damage to you is activated. Your opponent takes the damage instead.
8593,Performage Flame Eater,"During either player's turn, when a card or effect is activated that would inflict damage to you: You can activate this effect; you cannot Special Summon monsters for the rest of this turn, except ""Performage"" monsters, also Special Summon this card from your hand, and if you do, make that effect damage to you 0. If Summoned this way, banish it when it leaves the field. If this card is Normal or Special Summoned: Each player takes 500 damage."
12747,Wave-Motion Cannon,During your Main Phase: You can send this face-up card to the GY; inflict 1000 damage to your opponent for each of your Standby Phases that have passed since this card was activated.
5162,Gravedigger's Trap Hole,"When your opponent activates a monster effect in their hand or GY, or when your opponent's banished monster effect is activated: Negate its effect, and if you do, inflict 2000 damage to your opponent."
1471,Brutal Potion,"This card becomes an Equip Card, and equips to 1 monster you control. Once per turn, when you inflict damage to your opponent with a card effect, the equipped monster gains 1000 ATK until the End Phase."
10514,Solar Ray,Inflict 600 points of damage to your opponent's Life Points for each face-up LIGHT monster on your side of the field.
4394,Frightfur Leo,"""Edge Imp Saw"" + 1 ""Fluffal"" monster\nMust be Fusion Summoned and cannot be Special Summoned by other ways. You can target 1 face-up monster your opponent controls; destroy it, and if you do, inflict damage to your opponent equal to the destroyed monster's original ATK. You can only use this effect of ""Frightfur Leo"" once per turn. This card cannot attack your opponent directly during the turn you activate this effect."
4105,Fire Cracker,"(Quick Effect): You can discard this card; inflict 1000 damage to your opponent, and if you do, skip your next Draw Phase. You can only use this effect of ""Fire Cracker"" once per turn. Each time your opponent takes effect damage, place 1 counter on this card. Once per turn, during the End Phase: Remove all counters from this card that were placed by its effect, and if you do, inflict 300 damage to your opponent for each."
3201,Double Payback,"Activate only when you take 1000 or more damage from your opponent's card effect: Place 1 Payback Counter on this card for every 1000 damage you took. During the End Phase of your opponent's next turn: Destroy this card, and if you do, inflict 2000 damage to your opponent for each Payback Counter on this card."

In [263]:
new_cards["pay_lp"] = new_cards["desc"].str.contains(
    r"pay.*lp",
    case=False,
    na=False
)
new_cards["pay_lp"].value_counts()

pay_lp
False    12932
True       244
Name: count, dtype: int64

In [264]:
new_cards.loc[
    new_cards["pay_lp"],
    ["name", "desc"]
].sample(10)

,name,desc
1845,Chronomaly Temple - Trilithon,"If you control no monsters, or all monsters you control are ""Chronomaly"" monsters: You can pay 500 LP; immediately after this effect resolves, Normal Summon 1 ""Chronomaly"" monster from your hand. If a ""Chronomaly"" or ""Number"" Xyz Monster you control would activate an effect by detaching material, you can send this card to the GY instead of 1 of those materials. You can only use each effect of ""Chronomaly Temple - Trilithon"" once per turn."
7365,Messenger of Peace,"Monsters with 1500 or more ATK cannot declare an attack. Once per turn, during your Standby Phase, pay 100 LP or destroy this card."
9792,Ryu Senshi,"""Warrior Dai Grepher"" + ""Spirit Ryu""\r\nA Fusion Summon of this card can only be done with the above Fusion Materials. When a Normal Trap Card is activated (Quick Effect): You can pay 1000 LP; negate that effect. This card must be face-up on the field to activate and to resolve this effect. Negate the effects of any Spell Card that targets this card and destroy it."
10150,Seven Tools of the Bandit,"When a Trap Card is activated: Pay 1000 LP; negate the activation, and if you do, destroy it."
3923,Extra-Foolish Burial,"Pay half your LP; send 1 monster from your Extra Deck to the GY. You can only activate 1 ""Extra-Foolish Burial"" per turn. You cannot Set Spells/Traps during the turn you activate this card."
12350,Ursarctic Quint Charge,"Once per turn: You can pay 700 LP, then activate 1 of the following effects;\r\n● Add 1 ""Ursarctic"" monster from your GY to your hand.\r\n● Tribute 2 ""Ursarctic"" monsters (even if face-down), and if you do, Special Summon from your Extra Deck, 1 ""Ursarctic"" monster with a Level equal to the difference in Levels of those monsters, ignoring its Summoning conditions.\r\nWhen your ""Ursarctic"" Synchro Monster is destroyed by an opponent's attack: You can activate this effect; your opponent must shuffle cards into the Deck so the total number of cards in their field, hand, and GY is 7."
3015,Dinomorphia Domain,"During the Main Phase: Pay half your LP; Fusion Summon 1 ""Dinomorphia"" Fusion Monster from your Extra Deck, using monsters from your hand, Deck, or field as material. When your opponent activates a card or effect, while your LP are 2000 or less: You can banish this card from your GY; you take no effect damage from your opponent's card effects this turn. You can only activate 1 ""Dinomorphia Domain"" per turn."
2758,Decode Talker Heatsoul,"2+ Cyberse monsters with different Attributes\r\nGains 500 ATK for each monster it points to. (Quick Effect): You can pay 1000 LP; draw 1 card, then if your LP are 2000 or less, you can banish this card from the field, and if you do, Special Summon 1 Link-3 or lower Cyberse monster from your Extra Deck, except ""Decode Talker Heatsoul"". You can only use this effect of ""Decode Talker Heatsoul"" once per turn."
9357,Re-Cover,"If this card is in the Graveyard and your opponent has 5 or more cards in their Extra Deck than you do: You can pay 2000 LP; Special Summon this card, but banish it when it leaves the field. You can only use this effect of ""Re-Cover"" once per turn."
12254,Ultra Polymerization,"Pay 2000 LP; Fusion Summon 1 Fusion Monster from your Extra Deck, using 2 monsters you control as Fusion Materials. Neither player can activate cards or effects in response to this card's activation. You can banish this card from your GY, then target 1 Fusion Monster that was Fusion Summoned with this card's effect; Special Summon all the Fusion Materials used for its Fusion Summon from your GY, but change their ATK/DEF to 0, also they have their effects negated."

In [ ]:
# Detect Life Point recovery using a regular expression
new_cards["lp_gain"] = new_cards["desc"].str.contains(
    r"gain(?:s)?(?:\s+\S+){0,5}\s+LP",
    case=False,
    na=False,
    regex=True
)

new_cards["lp_gain"].value_counts()

lp_gain
False    12989
True       187
Name: count, dtype: int64

In [266]:
new_cards.loc[
    new_cards["lp_gain"],
    ["name", "desc"]
].sample(10)

,name,desc
1795,Child's Play,"Each time your opponent Summons a monster(s), gain 300 LP. Your monsters cannot be destroyed by battle while you have 10,000 or more LP."
5129,Graceful Tear,"Add 1 card from your hand to your opponent's hand, then gain 2000 LP."
1096,Binary Sorceress,"2 monsters, except Tokens\r\nThis card gains these effects based on the number of monsters co-linked to this card.\r\n● 1+: When a monster co-linked to this card battles your opponent's monster and inflicts battle damage to them: You can gain that much LP.\r\n● 2: Once per turn (Quick Effect): You can target 2 face-up monsters you control; until the end of this turn, halve the ATK of 1 monster, and if you do, add that lost ATK to the other monster."
10578,Soul Taker,"Target 1 face-up monster your opponent controls; destroy that target, then your opponent gains 1000 LP."
4916,"Gizmek Okami, the Dreaded Deluge Dragon","You can pay 1500 LP; destroy all monsters on the field that were Special Summoned from the Extra Deck, also you can only attack with 1 monster this turn. You can only use each of the following effects of ""Gizmek Okami, the Dreaded Deluge Dragon"" once per turn. If 2 or more monsters Special Summoned from the Extra Deck are on the field: You can Special Summon this card from your hand. If this card in your possession is sent to your GY by an opponent's card: You can banish 1 monster from your opponent's GY, then gain LP equal to its ATK."
4241,Floowandereeze and the Advent of Adventure,"Banish 1 Winged Beast monster from your hand or face-up field; add 1 ""Floowandereeze"" monster or ""Floowandereeze"" Field Spell from your Deck to your hand, then gain 500 LP. You can only activate 1 ""Floowandereeze and the Advent of Adventure"" per turn."
1142,Black Return,"When exactly 1 ""Blackwing"" monster (and no other monster) is Special Summoned: Target 1 face-up monster your opponent controls; gain LP equal to the ATK of that target, and if you do, return it to the hand."
11395,Telepathic Power,"When a Psychic-Type monster you control is destroyed by battle with an opponent's attacking monster: Target the opponent's monster; destroy that target, and if you do, gain LP equal to the destroyed monster's ATK on the field."
687,Aromalilith Rosemary,"2+ Plant monsters\r\nIf this card is Special Summoned: You can add 1 ""Aroma"" card from your Deck to your hand. If you gain LP, even during the Damage Step: You can Special Summon up to 3 ""Aroma"" monsters from your hand to your zones this card points to. You can Tribute 1 monster this card points to, then target 1 card on the field; banish it, and if you do, gain 1000 LP. You can only use each effect of ""Aromalilith Rosemary"" once per turn."
5275,Guard Penguin,"When you take damage from a card effect (except during the Damage Step): You can Special Summon this card from your hand, and if you do, gain LP equal to the damage you took."

In [267]:
new_cards[new_cards["name"]=="Blackwing Full Armor Master"][["name", "desc"]]

,name,desc
1222,Blackwing Full Armor Master,"1 ""Blackwing"" Tuner + 1+ non-Tuner monsters\r\nUnaffected by other cards' effects. Each time a monster your opponent controls activates its effect, place 1 Wedge Counter on that opponent's monster (max. 1) after that effect resolves. Once per turn: You can target 1 monster your opponent controls with a Wedge Counter; take control of it. Once per turn, during your End Phase: You can destroy all monsters on the field that have a Wedge Counter."

In [268]:
new_cards[new_cards["name"]=="Galaxy-Eyes Cipher Dragon"][["name", "desc"]]

,name,desc
4562,Galaxy-Eyes Cipher Dragon,"2 Level 8 monsters\nOnce per turn: You can detach 1 Xyz Material from this card, then target 1 face-up monster your opponent controls; monsters you control cannot attack your opponent directly for the rest of this turn, except this card, also take control of the targeted monster until the End Phase, but while this effect is applied, it has its effects negated, its ATK becomes 3000, also its name becomes ""Galaxy-Eyes Cipher Dragon""."

In [269]:
new_cards["change_control"] = new_cards["desc"].str.contains(
    "take control",
    case=False,
    na=False
)

new_cards["change_control"].value_counts()

change_control
False    13049
True       127
Name: count, dtype: int64

In [270]:
new_cards.loc[
    new_cards["change_control"],["name","desc"]
].sample(10)

,name,desc
4009,Falling Down,"Activate this card by targeting an opponent's monster; equip this card to it. Take control of it. Destroy this card unless you control an ""Archfiend"" card. During each of your opponent's Standby Phases: You take 800 damage."
2709,Darklord Enchantment,"Send 1 ""Darklord"" monster from your hand or face-up field to the GY; take control of 1 face-up monster your opponent controls until the End Phase. You can only activate 1 ""Darklord Enchantment"" per turn."
4969,Gladiator Taming,"If a face-up ""Gladiator Beast"" monster is on the field, activate 1 of these effects:\n● Select 1 face-up monster your opponent controls, and change its battle position.\n● Select 1 face-up ""Gladiator Beast"" monster your opponent controls, and take control of it until the End Phase."
10143,Service Puppet Play,"Target monsters your opponent controls, up to the number of ""Gimmick Puppet"" Xyz Monsters you control; take control of those monsters until the End Phase. If this card is in your GY, except the turn it was sent there, and you control a ""Gimmick Puppet"" Xyz Monster: You can banish this card, then target 1 Xyz Monster in either GY; Special Summon it to either field in Defense Position. You can only use each effect of ""Service Puppet Play"" once per turn."
1859,Chthonian Polymer,Activate only when your opponent Fusion Summons a Fusion Monster. Tribute 1 monster to take control of that Fusion Monster.
10759,Splash Capture,When your opponent Xyz Summons: Banish 2 Fish-Type monsters from your Graveyard to target that face-up Xyz Monster; take control of that target.
503,Apoqliphort Skybase,"Cannot be Special Summoned. Requires 3 ""Qli"" Tributes to Normal Summon/Set. If this card is Normal Summoned/Set, it is unaffected by Spell/Trap effects and by activated effects from any monster whose original Level/Rank is lower than this card's current Level. Once per turn: You can target 1 monster your opponent controls; take control of it until the End Phase."
7109,Mark of the Rose,"Activate this card by banishing 1 Plant monster from your GY, then target 1 face-up monster your opponent controls; equip this card to it. Take control of the equipped monster. Once per turn, during your End Phase: Negate this card's effect until your next Standby Phase."
5208,Graydle Cobra,"If this card in your Monster Zone is destroyed by battle or Trap effect and sent to your Graveyard: You can target 1 face-up monster your opponent controls; equip this card to that target. While this card is equipped to a monster by this effect, take control of that monster. When this card leaves the field, destroy the equipped monster."
12086,Triple Tactics Talent,"If your opponent has activated a monster effect during your Main Phase this turn: Activate 1 of these effects;\r\n● Draw 2 cards.\r\n● Take control of 1 monster your opponent controls until the End Phase.\r\n● Look at your opponent's hand, and choose 1 card from it to shuffle into the Deck.\r\nYou can only activate 1 ""Triple Tactics Talent"" per turn."

In [271]:
new_cards["change_battle_position"] = new_cards["desc"].str.contains(
    r"change.*position",
    case=False,
    na=False
)

new_cards["change_battle_position"].value_counts()

change_battle_position
False    12677
True       499
Name: count, dtype: int64

In [272]:
new_cards.loc[
    new_cards["change_battle_position"],
    ["name", "desc"]
].sample(10)

,name,desc
11102,Superheavy Samurai General Jade,"[ Pendulum Effect ] \nYou cannot Pendulum Summon monsters, except ""Superheavy Samurai"" monsters. This effect cannot be negated. Once per turn: You can target 1 ""Superheavy Samurai"" monster you control; increase its Level by 1 (even if this card leaves the field).\n[ Monster Effect ] \nYou can Tribute Summon this card by Tributing 1 ""Superheavy Samurai"" monster. When this card is Normal or Special Summoned: You can change its battle position. This card can attack while in face-up Defense Position. If it does, apply its DEF for damage calculation."
301,Amaze Attraction Rapid Racing,"Target 1 ""Amazement"" monster you control or 1 face-up monster your opponent controls; equip this card to it. You can activate the following effect, based on which player controls the equipped monster;\r\n● You: Target 1 card in your opponent's GY; change the equipped monster's battle position, and if you do, shuffle that target into the Deck.\r\n● Your opponent: Increase the equipped monster's Level by 1 (until the end of this turn), and if you do, change its battle position.\r\nYou can only use this effect of ""Amaze Attraction Rapid Racing"" once per turn."
6500,Legendary Wind-Up Key,"Change all face-up ""Wind-Up"" monsters you control to face-down Defense Position."
8623,Performapal Corn,"Once per turn, during your Main Phase, if this card was Normal or Special Summoned this turn: You can target 1 other ""Performapal"" monster you control with 1000 or less ATK; change both it and this card, that you control, from face-up Attack Position to Defense Position, and if you do, add 1 ""Odd-Eyes"" monster from your Deck to your hand. During your opponent's turn: You can banish 1 ""Performapal"" monster, except ""Performapal Corn"", and this card from your Graveyard; gain 500 LP (this is a Quick Effect)."
1549,"Buster Blader, the Dragon Destroyer Swordsman","1 ""Buster Blader"" + 1 Dragon-Type monster\nMust be Fusion Summoned and cannot be Special Summoned by other ways. This card cannot attack directly. This card gains 1000 ATK and DEF for each Dragon-Type monster your opponent controls or is in their Graveyard. Change all Dragon-Type monsters your opponent controls to Defense Position, also Dragon-Type monsters in your opponent's possession cannot activate their effects. If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent."
8656,Performapal Momoncarpet,"[ Pendulum Effect ] \nUnless you have a card in your other Pendulum Zone, destroy this card. While this card is in the Pendulum Zone, any battle damage you take becomes halved.\n[ Monster Effect ] \nFLIP: You can target 1 Set card on the field; destroy it. If this card is Special Summoned: You can change it to face-down Defense Position."
9651,Ritual Beast Inheritance,"Monsters your opponent controls lose 200 ATK for each different Type among the ""Ritual Beast"" monsters you control. You can only use each of the following effects of ""Ritual Beast Inheritance"" once per turn. You can reveal 1 ""Ritual Beast"" monster in your hand; add 1 ""Ritual Beast"" monster with a different Type from your Deck to your hand, then discard 1 card. If 2 or more monsters are Special Summoned to your field at the same time (except during the Damage Step): You can target 1 monster on the field; change its battle position."
5164,Gravekeeper's Assailant,"When this card declares an attack while ""Necrovalley"" is on the field: You can target 1 face-up monster your opponent controls; change that target's battle position."
10638,Speedroid Razorang,"Cannot attack the turn it is Normal Summoned. Once per turn: You can target 1 face-up monster on the field; change this card to Defense Position, and if you do, that target loses 800 ATK until the end of this turn."
5917,Intercept Wave,"All Synchro Monsters on the field are changed to Defense Position. And then, return all face-up Synchro Monsters to the Extra Deck during the End Phase."

In [273]:
new_cards["tribute"] = new_cards["desc"].str.contains(
    "tribute",
    case=False,
    na=False
)

new_cards["tribute"].value_counts()

tribute
False    11622
True      1554
Name: count, dtype: int64

In [274]:
new_cards.loc[
    new_cards["tribute"],
    ["name", "desc"]
].sample(10)

,name,desc
5762,Illusory Snatcher,"When you Tribute Summon a monster: You can Special Summon this card from your hand, and if you do, the Type, Attribute, and Level of this card become the same as that face-up Tribute Summoned monster."
3755,Esprit Bird Token,"This card can be used as a ""Shinobird Token"".\r\n\r\n*If used for another Token, apply that Token's Type/Attribute/Level/ATK/DEF."
5543,Hi-Speedroid Hagoita,"1 Tuner + 1 or more non-Tuner monsters\nDuring either player's turn: You can Tribute this card; increase the Levels of all monsters currently on the field by 1, until the end of this turn. If this card is in your Graveyard and you control a ""Speedroid"" Tuner monster: You can Special Summon this card, also you cannot Special Summon monsters for the rest of this turn, except WIND monsters. You can only use this effect of ""Hi-Speedroid Hagoita"" once per turn."
3160,Doomcaliber Knight,"Cannot be Special Summoned. If a monster effect is activated (Quick Effect): Tribute this face-up card; negate the activation, and if you do, destroy that monster."
6782,Machine Angel Absolute Ritual,"This card can be used to Ritual Summon any ""Cyber Angel"" Ritual Monster. You must also Tribute monsters from your hand or field and/or shuffle Fairy or Warrior-Type monsters from your Graveyard into the Deck, whose total Levels exactly equal the Level of the Ritual Monster you Ritual Summon."
1135,Black Magic Ritual,"This card is used to Ritual Summon ""Magician of Black Chaos"". You must also Tribute monsters from your hand or field whose total Levels equal 8 or more."
7118,Mask Change,"Target 1 ""HERO"" monster you control; send it to the GY, also, after that, if it left the field by this effect, Special Summon 1 ""Masked HERO"" monster from your Extra Deck with the same Attribute that the sent monster had when it was on the field (its original Attribute, if face-down)."
10353,"Simorgh, Lord of the Storm","Your opponent cannot target this Tribute Summoned card with Spell/Trap Cards or effects. You can only use each of the following effects of ""Simorgh, Lord of the Storm"" once per turn.\r\n● When a Spell/Trap Card or effect is activated (Quick Effect): You can Tribute 1 WIND Winged Beast monster, then target 1 card your opponent controls; shuffle it into the Deck.\r\n● When a Winged Beast monster you control is destroyed by battle while this card is in your GY: You can add this card to your hand."
6718,Lunalight Cat Dancer,"2 ""Lunalight"" monsters\nCannot be destroyed by battle. Once per turn, during your Main Phase 1: You can Tribute 1 other ""Lunalight"" monster; for the rest of this turn, the first time each monster your opponent controls would be destroyed by battle, it is not destroyed, also this card can attack all monsters your opponent controls, twice each, this turn. If this card declares an attack: Inflict 100 damage to your opponent."
1047,"Behold, Gate Guardian!","Activate this Skill during your Main Phase. Shuffle your entire hand into the Deck, then add 1 Level 11 monster from your Deck to your hand, and if you do, you can Special Summon up to 2 Level 7 monsters with different Attributes from your Deck and/or GY, but their ATK/DEF become 0, also their effects are negated. While you control ""Gate Guardian"", it gains the following effect.\r\n● Once while face-up on the field, when this card is targeted for an attack: You can change the attacking monster's ATK to 0, until the end of the Damage Step."

In [275]:
new_cards["discard"] = new_cards["desc"].str.contains(
    "discard",
    case=False,
    na=False
)

new_cards["discard"].value_counts()

discard
False    12297
True       879
Name: count, dtype: int64

In [276]:
new_cards.loc[
    new_cards["discard"],
    ["name", "desc"]
].sample(10)

,name,desc
11530,The Fabled Ganashia,"When this card is discarded to the Graveyard, Special Summon it. If this card is Special Summoned this way, it gains 200 ATK and is removed from play when it is removed from the field."
11753,Thunder Dragon Thunderstormech,"2+ Thunder monsters\r\nDuring your Main Phase, if you control this Link Summoned card: You can target 1 of your ""Thunder Dragon"" monsters that is banished or in your GY; apply that monster's effect that discards itself to activate, then place that monster on the top or bottom of your Deck. You can only use this effect of ""Thunder Dragon Thunderstormech"" once per turn. If a Thunder monster(s) you control would be destroyed by battle or card effect, you can banish 3 cards from your GY instead."
508,Appliancer Breakerbuncle,"During damage calculation, if an ""Appliancer"" monster you control battles an opponent's monster (Quick Effect): You can discard this card; for that battle, that monster you control cannot be destroyed, also you take no battle damage. If an ""Appliancer"" monster(s) you control would be destroyed by a card effect, you can banish this card from your field or GY instead."
3744,Erebus the Underworld Monarch,"You can Tribute Summon this card by Tributing 1 Tribute Summoned monster. If this card is Tribute Summoned: You can send 2 ""Monarch"" Spell/Trap Cards with different names from your hand and/or Deck to the Graveyard, and if you do, shuffle 1 card from your opponent's hand (at random), Graveyard, or their side of the field into the Deck. Once per turn, during either player's Main Phase, if this card is in your Graveyard: You can discard 1 ""Monarch"" Spell/Trap Card, then target 1 monster in your Graveyard with 2400 or more ATK and 1000 DEF; add it to your hand."
7344,Mermail Abyssbalaen,"You can discard 4 other ""Mermail"" monsters to the Graveyard; Special Summon this card from your hand. When you do: Target cards your opponent controls, up to the number of ""Mermail"" monsters in your Graveyard (if possible); this card gains 500 ATK, and if it does, destroy those targets (if any). You can Tribute 1 other face-up Attack Position ""Mermail"" monster; this card gains the following effect this turn.\n● At the start of the Damage Step, if this card battles a Defense Position monster: Destroy that monster."
1752,Chaos Hunter,When your opponent Special Summons a monster (except during the Damage Step): You can discard 1 card; Special Summon this card from your hand. Your opponent cannot banish cards.
9787,Ruthless Means,"Once per Duel, during your Main Phase, if you control an ""Evil HERO"" monster, you can discard 1 card to make 1 face-up monster your opponent controls lose ATK equal to its own DEF, or lose DEF equal to its own ATK (your choice)."
1457,Brotherhood of the Fire Fist - Ram,"When this card is Normal Summoned: You can discard 1 card, then target 1 ""Fire Formation"" Spell/Trap you control; Set 1 ""Fire Formation"" Spell/Trap with a different name directly from your Deck. If this card is Special Summoned by the effect of a ""Fire Fist"" monster: You can Set 1 ""Fire Formation"" Spell/Trap directly from your Deck, with a different name from the cards in your GY. You can only use each effect of ""Brotherhood of the Fire Fist - Ram"" once per turn."
2683,Dark World Archives,"During your Main Phase: You can discard 1 ""Dark World"" monster, and if you do, ""Dark World"" monsters you currently control gain ATK equal to the Level the discarded monster had in the hand x 100, until the end of this turn. If a monster whose original Type is Fiend is discarded from your hand by the effect of a ""Dark World"" card or an opponent's card effect, even during the Damage Step: You can discard 1 card, then draw 2 cards. You can only use each effect of ""Dark World Archives"" once per turn."
8486,Paleozoic Dinomischus,"Target 1 face-up card on the field; discard 1 card, and if you do, banish it. Once per Chain, when a Trap Card is activated while this card is in your GY: You can Special Summon this card as a Normal Monster (Aqua/WATER/Level 2/ATK 1200/DEF 0). (This card is NOT treated as a Trap.) If Summoned this way, this card is unaffected by monster effects, also banish it when it leaves the field."

In [277]:
new_cards["bounce"] = new_cards["desc"].str.contains(
    r"return.*to the hand",
    case=False,
    na=False,
    regex=True
)

new_cards["bounce"].value_counts()

bounce
False    12707
True       469
Name: count, dtype: int64

In [278]:
new_cards.loc[
    new_cards["bounce"],
    ["name", "desc"]
].sample(10)

,name,desc
6955,Magnetic Field,"If you control a Level 4 or lower EARTH Rock-Type monster: You can target 1 Level 4 or lower ""Magnet Warrior"" monster in your Graveyard; Special Summon it. You can only use this effect of ""Magnetic Field"" once per turn. Once per turn, at the end of the Damage Step, when an EARTH Rock-Type monster you control battled an opponent's monster, but the opponent's monster was not destroyed by the battle: You can return that opponent's monster to the hand."
8698,Performapal Trampolynx,"[ Pendulum Effect ] \nWhen you Pendulum Summon a monster(s): You can target 1 card in either player's Pendulum Zone; return it to the hand. You can only use this effect of ""Performapal Trampolynx"" once per turn.\n[ Monster Effect ] \nWhen this card is Normal Summoned: You can target 1 card in either player's Pendulum Zone; return it to the hand."
4900,Gishki Natalia,"Cannot be Special Summoned. During the End Phase of the turn this card was Normal Summoned or flipped face-up: Return it to the hand. When this card is Normal Summoned or flipped face-up: You can target 1 ""Gishki"" monster in your Graveyard; return that target to the top of the Deck."
10167,Shaddoll Zefranaga,"[ Pendulum Effect ] \nYou cannot Pendulum Summon monsters, except ""Shaddoll"" and ""Zefra"" monsters. This effect cannot be negated.\n[ Monster Effect ] \nIf this card is Pendulum Summoned or sent to the GY: You can target 1 card in either player's Pendulum Zone; return it to the hand. You must have a ""Zefra"" card in your Pendulum Zone to activate and to resolve this effect. You can only use this effect of ""Shaddoll Zefranaga"" once per turn."
6214,Kelbek,A monster that attacks this card returns to the hand. Damage calculation is applied normally.
8441,Overwind,"Target 1 face-up ""Wind-Up"" monster you control; its ATK and DEF are doubled, and it returns to the hand during the End Phase. You can only activate 1 ""Overwind"" per turn."
7878,"Neiroy, the Dream Mirror Disciple","If a ""Dream Mirror"" monster(s) is on the field: You can Special Summon this card from your hand, then, you can make this card become DARK. If this card is Special Summoned by the effect of a ""Dream Mirror"" monster: Activate this effect; if ""Dream Mirror of Joy"" is on the field, you can return 1 Spell/Trap your opponent controls to the hand, also, after that, if ""Dream Mirror of Terror"" is on the field, draw 1 card, then shuffle 1 card from your hand into the Deck. You can only use each effect of ""Neiroy, the Dream Mirror Disciple"" once per turn."
4651,Gem-Elephant,"During your Main Phase: You can return this face-up card on the field to the hand. During damage calculation, if this card attacked or was attacked: You can send 1 Normal Monster from your hand to the Graveyard; this card gains 1000 DEF."
10863,Starry Knight Ciel,"If this card is in your hand: You can return 1 ""Starry Knight"" monster or 1 Level 7 LIGHT Dragon monster you control to the hand, except ""Starry Knight Ciel""; Special Summon this card. If you control no monsters: You can banish this card from your GY; Special Summon 1 Level 7 LIGHT Dragon monster from your hand. You can only use each effect of ""Starry Knight Ciel"" once per turn."
10351,"Simorgh, Bird of Protection","When this card is Normal Summoned: You can target 1 card in your opponent's Spell & Trap Zone; return it to the hand. If this card is in your GY and your opponent controls no cards in their Spell & Trap Zone: You can Special Summon this card in Defense Position, but banish it when it leaves the field, also you cannot Special Summon monsters for the rest of this turn, except Winged Beast monsters. You can only use each effect of ""Simorgh, Bird of Protection"" once per turn."

In [279]:
new_cards["shuffle_into_deck"] = new_cards["desc"].str.contains(
    r"shuffle.*into the Deck",
    case=False,
    na=False,
    regex=True
)

new_cards["shuffle_into_deck"].value_counts()

shuffle_into_deck
False    12727
True       449
Name: count, dtype: int64

In [280]:
new_cards.loc[
    new_cards["shuffle_into_deck"],
    ["name", "desc"]
].sample(10)

,name,desc
7695,Mudora the Sword Oracle,"You can discard 1 other EARTH Fairy monster; Special Summon this card from your hand, then you can place 1 ""Gravekeeper's Trap"" from your Deck face-up in your Spell & Trap Zone. (Quick Effect): You can banish this card from your field or GY, then target up to 3 cards in any GY(s), or up to 5 if ""Exchange of the Spirit"" is on your field or in your GY; shuffle them into the Deck. You can only use each effect of ""Mudora the Sword Oracle"" once per turn."
10242,Shinobaroness Peacock,"You can Ritual Summon this card with ""Shinobird's Calling"". Must be Ritual Summoned, and cannot be Special Summoned by other ways. If this card is Ritual Summoned: You can shuffle up to 3 Spell/Trap Cards your opponent controls into the Deck, then you can Special Summon 1 Level 4 or lower Spirit monster from your Deck, ignoring its Summoning conditions. Once per turn, during the End Phase, if this card was Special Summoned this turn: Return it to the hand, and if you do, Special Summon 2 ""Shinobird Tokens"" (Winged Beast-Type/WIND/Level 4/ATK 1500/DEF 1500)."
3529,"Ehren, Lightsworn Monk","If this card attacks a Defense Position monster, before damage calculation: Shuffle that monster into the Deck. Once per turn, during your End Phase: Send the top 3 cards of your Deck to the Graveyard."
11818,Time-Space Trap Hole,"When your opponent Special Summons a monster(s) from the hand or Extra Deck: Shuffle that monster(s) into the Deck, then you lose 1000 LP for each returned monster."
9968,Satellarknight Sirius,"If this card is Summoned: You can target 5 ""tellarknight"" monsters in your Graveyard; shuffle all 5 into the Deck, then draw 1 card. You can only use this effect of ""Satellarknight Sirius"" once per turn."
8297,Ogdoadic Daybreak,"Tribute 1 Reptile monster; for every 2 Levels that Tributed monster had on the field, Special Summon up to 1 ""Ogdoadic Token"" (Reptile/DARK/Level 2/ATK 0/DEF 0). During your Main Phase: You can banish this card from your GY, then target 1 of your banished Reptile monsters; shuffle it into the Deck, then you can send 1 Reptile monster from your Deck to the GY. You can only use each effect of ""Ogdoadic Daybreak"" once per turn."
7655,Morphtronic Impact Return,"Target up to 2 Spells/Traps your opponent controls; shuffle 1 ""Morphtronic"" monster from your hand into the Deck, and if you do, shuffle the targeted card(s) into the Deck. You can banish this card from your GY, then target 1 of your ""Morphtronic"" monsters that is banished or in your GY; Special Summon it in Defense Position. You can only use 1 ""Morphtronic Impact Return"" effect per turn, and only once that turn."
6803,Madolche Anjelly,"If this card in your possession is destroyed by your opponent's card (by battle or card effect) and sent to your Graveyard: Shuffle this card into the Deck. You can Tribute this card; Special Summon 1 ""Madolche"" monster from your Deck, but shuffle it into the Deck during the End Phase of your next turn. You can only use this effect of ""Madolche Anjelly"" once per turn. That Special Summoned monster cannot be destroyed by battle."
9893,Salamangreat Foxy,"When this card is Normal Summoned: You can excavate the top 3 cards of your Deck, and if you do, you can add 1 excavated ""Salamangreat"" card to your hand, also shuffle the rest into the Deck. If this card is in your GY, and a face-up Spell/Trap is on the field: You can discard 1 ""Salamangreat"" card; Special Summon this card, then you can destroy 1 face-up Spell/Trap on the field. You can only use 1 ""Salamangreat Foxy"" effect per turn, and only once that turn."
7385,Metalfoes Mithrilium,"1 ""Metalfoes"" monster + 1 Pendulum Monster\r\nYou can target 2 ""Metalfoes"" cards in your GY and 1 card on the field; shuffle the targets from your GY into the Deck, and if you do, return the target on the field to the hand. You can only use this effect of ""Metalfoes Mithrilium"" once per turn. If this card is sent from the field to the GY: You can Special Summon 1 ""Metalfoes"" Pendulum Monster from your GY or face-up Extra Deck."

## Phase 3b: Feature Refinement

### Draw

In [ ]:
# Refine draw detection to include variable card quantities
new_cards["can_draw"] = new_cards["desc"].str.contains(
    r"\bdraw\b[^.;\n]*\bcards?\b",
    case=False,
    na=False
)

In [282]:
new_cards.loc[
    new_cards["can_draw"],
    ["name", "desc"]
].sample(15)

,name,desc
4628,Gearbreed,"During your Draw Phase, instead of conducting your normal draw: You can add 1 Equip Spell from your Deck or GY to your hand. If you control an Equip Spell: You can place 1 FIRE Warrior monster or 1 Gemini monster from your GY on the bottom of your Deck; draw 1 card. You can only use each effect of ""Gearbreed"" once per turn."
858,Backup Team,"Draw cards equal to the number of cards your opponent controls, then place cards from your hand on the bottom of the Deck in any order, equal to the number of cards you drew. During the End Phase, if your opponent controls more cards than you do while this card is in your GY: You can Set this card, but banish it when it leaves the field. You can only use 1 ""Backup Team"" effect per turn, and only once that turn."
13153,Yosenju Wind Worship,"If you control 3 or more ""Yosenju"" Monster Cards with different names: Return as many ""Yosenju"" Monster Cards you control to the hand as possible, then you can draw until you have 5 cards in your hand. You can only activate 1 ""Yosenju Wind Worship"" per turn."
2221,Cup of Ace,Toss a coin: ● Heads: Draw 2 cards. ● Tails: Your opponent draws 2 cards.
10423,Sky Scourge Norleras,"This card cannot be Normal Summoned or Set. This card cannot be Special Summoned except by removing from play 1 LIGHT Fairy-Type monster and 3 DARK Fiend-Type monsters in your Graveyard. You can pay 1000 Life Points to send all cards on the field and in both players' hands to the Graveyard, then you draw 1 card."
4019,Fantastical Dragon Phantazmay,"If your opponent Special Summons a Link Monster(s) (except during the Damage Step): You can Special Summon this card from your hand, draw cards equal to the number of Link Monsters your opponent controls +1, then shuffle cards from your hand into the Deck equal to the number of Link Monsters they control. When your opponent activates a card or effect that targets a monster(s) you control (Quick Effect): You can discard 1 card; negate the activation, and if you do, destroy it. You can only use each effect of ""Fantastical Dragon Phantazmay"" once per turn."
191,Albion the Shrouded Dragon,"This card's name becomes ""Fallen of Albaz"" while on the field or in the GY. If this card is in your hand or GY: You can send 1 ""Fallen of Albaz"" or 1 ""Branded"" Spell/Trap from your hand or Deck to the GY; apply the following effect based on where you sent it from.\r\n● Hand: Special Summon this card.\r\n● Deck: Place this card on the bottom of the Deck, then, if you placed this card from your hand, draw 1 card.\r\nYou can only use this effect of ""Albion the Shrouded Dragon"" once per turn."
11081,Super-Ancient Dinobeast,You can Tribute Summon this card in face-up Attack Position by Tributing 1 Dinosaur monster. When a Dinosaur monster(s) is Special Summoned from your GY while this monster is on the field (except during the Damage Step): You can draw 1 card.
2753,Deck Devastation Virus,"Tribute 1 DARK monster with 2000 or more ATK; look at your opponent's hand, all monsters they control, and all cards they draw until the end of their 3rd turn after this card's activation, and destroy all those monsters with 1500 or less ATK."
5891,Infinitrack Tunneller,"You can Tribute 1 EARTH Machine monster; Special Summon this card from your hand in Defense Position. You can banish this card from your GY, then target 5 EARTH Machine monsters in your GY; shuffle them into the Deck, then draw 2 cards. You can only use each effect of ""Infinitrack Tunneller"" once per turn."
6350,Kuraz the Light Monarch,"When this card is Normal or Special Summoned: You can target up to 2 cards on the field; destroy those targets, and if you do, each player can draw 1 card for each of the cards they controlled that was destroyed by this effect. This card cannot attack during the turn it is Normal or Special Summoned."
2515,Danger! Chupacabra!,"You can reveal this card in your hand; your opponent randomly chooses 1 card from your entire hand, then you discard the chosen card. Then, if the discarded card was not ""Danger! Chupacabra!"", Special Summon 1 ""Danger! Chupacabra!"" from your hand, and if you do, draw 1 card. If this card is discarded: You can target 1 ""Danger!"" monster in your GY, except ""Danger! Chupacabra!""; Special Summon it. You can only use this effect of ""Danger! Chupacabra!"" once per turn."
3346,Drastic Draw,"Banish all monsters you control (min. 2); draw 3 cards. You cannot Normal or Special Summon the turn you activate this card, except Cyberse monsters. You can only activate 1 ""Drastic Draw"" per turn."
925,Batteryman Micro-Cell,"FLIP: Special Summon 1 Level 4 or lower ""Batteryman"" monster from your Deck, except ""Batteryman Micro-Cell"". After this card has been flipped face-up, when it is destroyed by battle and sent to the Graveyard, draw 1 card."
2017,Constellar Star Chart,"Once per turn, when a ""Constellar"" Xyz Monster(s) is Special Summoned to your side of the field (except during the Damage Step): You can draw 1 card."

In [283]:
new_cards["can_draw"].value_counts()

can_draw
False    12401
True       775
Name: count, dtype: int64

### Destroy

In [284]:
new_cards.loc[
    new_cards["desc"].str.contains(
        "destroy", case=False, na=False
    ) & ~new_cards["can_destroy"],
    ["name", "desc"]
].sample(15)

,name,desc
11935,Trance Archfiend,"Once per turn: You can discard 1 Fiend-Type monster, and if you do, this card gains 500 ATK until the end of this turn. When this card you control is destroyed and sent to your Graveyard: You can target 1 of your banished DARK monsters; add that target to your hand."
620,Armed Changer,"Send 1 Equip Spell Card from your hand to the Graveyard to activate this card. If the equipped monster destroys a monster by battle, the controller of this Equip Card can add 1 monster with ATK equal to or less than the equipped monster from their Graveyard to their hand."
1753,Chaos Infinity,"Change as many Defense Position monsters on the field as possible to face-up Attack Position, then Special Summon 1 ""Meklord"" monster from your Deck or Graveyard, but its effects are negated, also it is destroyed during the End Phase."
1397,Branded Opening,"Discard 1 card, then take 1 ""Despia"" monster from your Deck, and either add it to your hand or Special Summon it in Defense Position, also for the rest of this turn after this card resolves, you cannot Special Summon monsters from the Extra Deck, except Fusion Monsters. If a Fusion Monster(s) you control would be destroyed by card effect, you can banish this card from your GY instead. You can only use each effect of ""Branded Opening"" once per turn."
2117,Crimson Nova Trinity the Dark Cubic Lord,"3 x ""Crimson Nova the Dark Cubic Lord""\nMust be Fusion Summoned with the above Fusion Materials and cannot be Special Summoned by other ways. Cannot be targeted, or destroyed by, your opponent's card effects. When this card declares an attack: Halve your opponent's LP. When this card destroys a monster by battle: You can activate this effect; this card can make a second attack during this Battle Phase. If you take effect damage: Inflict damage to your opponent equal to the damage you took."
9498,Relinkuriboh,"If this card is Tributed: Draw 1 card. If your monster would be destroyed by battle, you can banish this card from your GY instead."
11632,The Sacred Waters in the Sky,"Activate 1 ""The Sanctuary in the Sky"" directly from your Deck, or add 1 monster that mentions ""The Sanctuary in the Sky"" from your Deck to your hand, then, if ""The Sanctuary in the Sky"" is on the field or in either GY, you can gain 500 LP for each ""Hyperion"" and ""The Agent"" monster you control. If your monster that mentions ""The Sanctuary in the Sky"" would be destroyed by battle, you can banish this card from your GY instead. You can only use each effect of ""The Sacred Waters in the Sky"" once per turn."
7780,Myutant Expansion,"When you activate this card: You can take 1 Level 4 or lower ""Myutant"" monster from your Deck, and either add it to your hand or Special Summon it. If a Level 8 or higher ""Myutant"" monster(s) you control would be destroyed by card effect, you can banish this card you control instead. You can only activate 1 ""Myutant Expansion"" per turn."
6196,Kashtira Akstra,"If a face-up ""Kashtira"" Xyz Monster(s) you control is destroyed by battle or card effect: Banish 1 ""Visas Starfrost"" from your hand, your Deck, or your Monster Zone, and if you do, Special Summon 1 ""Vicious Astraloud"" from your Extra Deck, ignoring its Summoning conditions. If this card is banished: You can target 1 of your banished ""Visas Starfrost""; add it to your hand. You can only use each effect of ""Kashtira Akstra"" once per turn."
11314,T.G. Halberd Cannon/Assault Mode,"Cannot be Normal Summoned/Set. Must be Special Summoned with ""Assault Mode Activate"". You can only use each of the following effects of ""T.G. Halberd Cannon/Assault Mode"" once per turn.\r\n● When your opponent would Summon a monster (Quick Effect): You can negate the Summon, and if you do, banish that monster and all Special Summoned monsters your opponent controls.\r\n● When this card on the field is destroyed: You can target 1 ""T.G. Halberd Cannon"" in your GY; Special Summon it, ignoring its Summoning conditions."
10091,Secret Six Samurai - Kizaru,"When this card is Special Summoned: You can add from your Deck to your hand, 1 ""Six Samurai"" monster with a different Attribute from every monster you control. If exactly 1 ""Six Samurai"" monster you control (and no other cards) would be destroyed by card effect, you can banish this card from your GY instead."
1298,Blue-Eyes Chaos Dragon,"You can Ritual Summon this card with ""Chaos Form"". Must be Ritual Summoned. Your opponent cannot target this card with card effects, also it cannot be destroyed by your opponent's card effects. If this card was Ritual Summoned using ""Blue-Eyes White Dragon"", when it declares an attack: You can change the battle positions of as many monsters your opponent controls as possible, and if you do, the ATK/DEF of those changed monsters become 0, also, this turn, if this card attacks a Defense Position monster, inflict piercing battle damage."
11333,TG-SX1,"When a ""T.G."" monster you control destroys an opponent's monster by battle and sends it to the Graveyard: Target 1 ""T.G."" Synchro Monster in your Graveyard; Special Summon that target."
8289,Odd-Eyes Wizard Dragon,"If this card is in your hand: You can Tribute 1 DARK monster; send 1 ""Odd-Eyes Dragon"" from your hand, Deck, or face-up field to the GY, and if you do, Special Summon this card. If this card in your possession is destroyed by an opponent's card and sent to your GY: You can Special Summon 1 ""Odd-Eyes"" monster from your Deck or GY, except ""Odd-Eyes Wizard Dragon"", then you can add 1 ""Spiral Flame Strike"" from your Deck to your hand."
9923,Salvagent Driver,"If a Cyberse Link Monster you control is destroyed by an opponent's card effect while this card is in your hand or GY (except during the Damage Step): You can Special Summon this card. You can discard 1 Spell, then target 1 Cyberse monster in your GY; Special Summon it, but it cannot attack directly this turn. You can only use each effect of ""Salvagent Driver"" once per turn."

In [285]:
new_cards.loc[
    new_cards["can_destroy"],
    ["name", "desc"]
].sample(15)

,name,desc
12266,Unauthorized Bootup Device,"Once per turn, you can either: Target 1 face-up monster you control; equip this card to that target, OR: Unequip this card and Special Summon it. If the equipped monster would be destroyed by battle or card effect, destroy this card instead. If this card is destroyed and sent to the GY while equipped to a monster: You can Special Summon this card. You can only use this effect of ""Unauthorized Bootup Device"" once per turn."
2753,Deck Devastation Virus,"Tribute 1 DARK monster with 2000 or more ATK; look at your opponent's hand, all monsters they control, and all cards they draw until the end of their 3rd turn after this card's activation, and destroy all those monsters with 1500 or less ATK."
13041,XX-Saber Hyunlei,"1 Tuner + 1 or more non-Tuner ""X-Saber"" monsters\nWhen this card is Synchro Summoned, you can select and destroy up to 3 Spell or Trap Cards on the field."
650,Armor Ninjitsu Art of Alchemy,"If you control a ""Ninjitsu Art"" card: Destroy as many other ""Ninjitsu Art"" cards you control as possible, then draw 2 cards."
6464,"Lector Pendulum, the Dracoverlord","[ Pendulum Effect ] \nNegate the effects of face-up Pendulum Monsters while your opponent controls them.\n[ Monster Effect ] \nAt the start of the Damage Step, if this card battles a Pendulum Monster: Destroy both that monster and this card."
601,Archnemeses Eschatos,"Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand) by banishing 3 monsters with different Types from your GY and/or face-up field. Cannot be destroyed by card effects. You can declare 1 Monster Type on the field; destroy all monsters on the field with that Type, also until the end of the next turn, neither player can Special Summon monsters with that Type. You can only use this effect of ""Archnemeses Eschatos"" once per turn."
5754,Il Blud,"This card is treated as a Normal Monster while face-up on the field or in the GY. While this card is a Normal Monster on the field, you can Normal Summon it to have it become an Effect Monster with this effect.\n● Once per turn: You can Special Summon 1 Zombie monster from your hand or from either GY, but if this card leaves the field, destroy all Zombie monsters Special Summoned by this effect."
8456,PSY-Framegear Beta,"Cannot be Normal Summoned/Set. Must be Special Summoned by a card effect, and cannot be Special Summoned by other ways. When an opponent's monster declares an attack while you control no monsters: You can Special Summon both this card from your hand and 1 ""PSY-Frame Driver"" from your hand, Deck, or Graveyard, and if you do, destroy the attacking monster, then end the Battle Phase. During the End Phase, banish the face-up monsters Special Summoned by this effect."
3535,Ekibyo Drakmord,"The equipped monster cannot attack. Destroy the equipped monster at the end of its controller's 2nd turn after this card is activated. At that time, this card is returned to the owner's hand."
10027,Scrap Mind Reader,"Once per turn, while this card is in your Graveyard during your Main Phase 2, you can select 1 face-up ""Scrap"" monster you control, except ""Scrap Mind Reader"". Destroy that monster and Special Summon this card from the Graveyard. If you do, remove this card from play when it is removed from the field. If this card is used as a Synchro Material Monster, all other Synchro Material Monsters must be ""Scrap"" monsters."
8061,Nordic Relic Laevateinn,Target 1 face-up monster on the field that destroyed a monster by battle this turn; destroy it. Cards and effects cannot be activated in response to this card's activation.
11276,Synchro Deflector,Activate only when a face-up Synchro Monster you control is selected as an attack target. Negate the attack and destroy 1 monster your opponent controls.
8440,Overwhelm,Activate only while you control a face-up Level 7 or higher monster that was Tribute Summoned. Negate the activation of a Trap Card or Effect Monster's effect and destroy that card.
1874,Citadel Whale,"If this card is in your hand or GY: You can Tribute 2 WATER monsters; Special Summon this card. You can only use this effect of ""Citadel Whale"" once per turn. If this card is Special Summoned: You can Set 1 ""Sea Stealth Attack"" directly from your Deck. Once per turn, when your opponent activates a card or effect that targets 1 WATER monster you control (and no other cards) (Quick Effect): You can negate the activation, and if you do, destroy that card."
3502,Ebon High Magician,"2 Level 7 Spellcaster-Type monsters\nWhile this card has Xyz Material, you can activate a Quick-Play Spell Card or a Trap Card from your hand during your opponent's turn by detaching 1 Xyz Material from this card at activation. If this Xyz Summoned card is destroyed by battle and sent to the Graveyard, or if this Xyz Summoned card you control is sent to your Graveyard by an opponent's card effect: You can Special Summon 1 DARK Spellcaster-Type monster from your hand or Deck, then you can destroy 1 card on the field."

### Banish

In [ ]:
# Match banish and banishing as whole words
new_cards.loc[
    new_cards["can_banish"],
    ["name", "desc"]
].sample(15)

,name,desc
7023,Malefic Red-Eyes Black Dragon,"Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand) by banishing 1 ""Red-Eyes Black Dragon"" from your Deck. There can only be 1 ""Malefic"" monster on the field. Other monsters you control cannot declare an attack. If there is no face-up Field Spell on the field, destroy this card."
4451,Fusion Gate,"While this card is on the field: The turn player can Fusion Summon 1 Fusion Monster from their Extra Deck, by banishing Fusion Materials listed on it from their hand or field."
9431,Red Supernova Dragon,"3 Tuners + 1+ non-Tuner Synchro Monsters\r\nMust first be Synchro Summoned. Gains 500 ATK for each Tuner in your GY. Cannot be destroyed by your opponent's card effects. Once per turn, when your opponent's monster effect is activated, or when an opponent's monster declares an attack (Quick Effect): You can activate this effect; banish this card, also banish all cards your opponent controls. Once per turn, during your next End Phase after this card was banished by its own effect: Special Summon this banished card."
12577,Vivid Knight,"During either player's turn (except during the Damage Step), when your opponent targets exactly 1 LIGHT Beast-Warrior-Type monster you control (and no other cards) for an attack, or with a card effect: Banish that monster you control until your next Standby Phase, and if you do, Special Summon this card from your hand."
3503,Ebon Illusion Magician,"2 Level 7 monsters\nYou can also Xyz Summon this card by using a Rank 6 Spellcaster-Type Xyz Monster you control as the Xyz Material. (Xyz Materials attached to that monster also become Xyz Materials on this card.) Once per turn: You can detach 1 Xyz Material from this card; Special Summon 1 Spellcaster-Type Normal Monster from your hand or Deck. When a Spellcaster-Type Normal Monster declares an attack: You can target 1 card your opponent controls; banish it. You can only use this effect of ""Ebon Illusion Magician"" once per turn."
9193,REINFORCE!,"(This card is always treated as a ""Rescue-ACE"" card.)\r\nTarget 1 ""Rescue-ACE"" monster you control; for the rest of this turn, that monster you control gains 1500 ATK/DEF, is unaffected by your opponent's monster effects, and the next time it would be destroyed by battle, it is not destroyed. You can banish this card from your GY, then target 1 ""Rescue-ACE"" Spell in your GY; Set that card. You can only use this effect of ""REINFORCE!"" once per turn."
8463,"Paces, Light of the Ghoti","You can banish this card you control; Special Summon 1 Fish monster from your hand, except ""Paces, Light of the Ghoti"". During the Standby Phase of the next turn after this card was banished: You can Special Summon this banished card. During your opponent's Main Phase, if this card was Special Summoned this turn, you can (Quick Effect): Immediately after this effect resolves, Synchro Summon 1 Fish Synchro Monster using this card you control. You can only use each effect of ""Paces, Light of the Ghoti"" once per turn."
1930,Cocatorium the Heavy Metal Avian,"If this card is in your hand or GY: You can Tribute 1 Beast, Beast-Warrior, or Winged Beast monster; Special Summon this card, but banish it when it leaves the field. You can banish 1 Level 4 or lower Beast, Beast-Warrior, or Winged Beast monster from your Deck; this card's name becomes that banished monster's name, also it becomes the same Type, Attribute and Level as that monster's, until the End Phase. You can only use each effect of ""Cocatorium the Heavy Metal Avian"" once per turn."
10066,Sealing Ceremony of Katon,Once per turn: You can banish 1 FIRE monster from your Graveyard to target 1 card in your opponent's Graveyard; banish that target.
3061,Disposable Learner Device,"The equipped monster gains 200 ATK for each monster in your GY. During the End Phase, if this card is in the GY because it was sent there from the field this turn: You can Set this card, but banish it when it leaves the field. You can only use this effect of ""Disposable Learner Device"" once per turn."
6488,Legendary Knight Critias,"Cannot be Normal Summoned/Set. Must be Special Summoned with ""Legend of Heart"". When this card is Special Summoned: You can target 1 face-up Spell/Trap on the field; banish that target. When this card is targeted for an attack: You can target 1 Trap in your GY; Set that target. It can be activated this turn."
11940,Transcendosaurus Drillygnathus,"2 Level 6 monsters\r\nWhile this card has no materials, if it battles a monster, any battle damage it inflicts to your opponent is doubled. You can only use each of the following effects of ""Transcendosaurus Drillygnathus"" once per turn. You can detach 1 material from this card, then target 1 of your banished Dinosaur monsters; Special Summon it. If this card is destroyed: You can shuffle 1 Normal Monster from your GY into the Deck, then you can Special Summon this card."
11172,Survival's End,"Destroy as many Normal Monsters on the field as possible, and if you do, Special Summon Level 4 or lower Dinosaur-Type monsters from your Deck, up to the number destroyed, but destroy them during the End Phase. You can banish this card from your Graveyard, then target 1 Dinosaur-Type monster you control and 1 card your opponent controls; destroy them."
7316,Mementotlan Bone Party,"Destroy 1 ""Memento"" monster in your hand or face-up field, take 1 ""Memento"" monster from your Deck with a different name, and either add it to your hand or Special Summon it in Defense Position. During your Main Phase: You can banish this card from your GY, then target 1 ""Memento"" monster you control; if it attacks a Defense Position monster this turn, inflict piercing battle damage to your opponent. You can only use each effect of ""Mementotlan Bone Party"" once per turn."
7997,Ninjitsu Art Tool - Iron Digger,"The equipped monster gains 500 ATK, also it is treated as a ""Ninja"" monster. You can only use each of the following effects of ""Ninjitsu Art Tool - Iron Digger"" once per turn. You can banish 1 ""Ninja"" monster from your GY, then target 1 card on the field; destroy it. If this card is sent from the field to the GY: You can target 1 of your banished ""Ninja"" monsters; add it to your hand or Special Summon it in face-down Defense Position."

In [289]:
new_cards["can_banish"] = new_cards["desc"].str.contains(
    r"\bbanish(?:ing)?\b",
    case=False,
    na=False
)

### Burn

In [291]:
new_cards.loc[
    new_cards["desc"].str.contains("inflict", case=False, na=False)
    & ~new_cards["burn"],
    ["name", "desc"]
].sample(15)

,name,desc
5021,Goe Goe the Gallant Ninja,When this card inflicts Battle Damage to your opponent: Your opponent must discard 2 random cards. Your opponent must have at least 5 cards in their hand for you to activate and to resolve this effect.
12597,Volcanic Counter,"When you take battle damage while this card is in your Graveyard: Banish it from your Graveyard, then if there is a FIRE monster other than ""Volcanic Counter"" in your Graveyard, inflict damage to your opponent equal to the amount of battle damage you took."
3804,Evil HERO Wild Cyclone,"""Elemental HERO Avian"" + ""Elemental HERO Wildheart""\nMust be Special Summoned with ""Dark Fusion"" and cannot be Special Summoned by other ways. If this card attacks, your opponent cannot activate any Spell/Trap Cards until the end of the Damage Step. When this card inflicts Battle Damage to your opponent: Destroy all face-down Spell and Trap Cards your opponent controls."
5818,Infernity Dwarf,"While you have no cards in your hand, if a monster you control attacks a Defense Position monster, inflict piercing battle damage to your opponent."
2995,Dino Destruction,"Activate this Skill during your Main Phase. Once per turn, you can choose 1 Level 6 or higher Dinosaur monster you control. This turn, if it attacks a Defense Position monster, inflict piercing battle damage. Flip this card over at the end of the turn you activated this Skill."
2659,Dark Scorpion Combination,"You can only activate this card when there are ""Don Zaloog"", ""Cliff the Trap Remover"", ""Dark Scorpion - Chick the Yellow"", ""Dark Scorpion - Gorg the Strong"", and ""Dark Scorpion - Meanae the Thorn"" face-up on your side of the field. During this turn, any of these 5 cards can attack your opponent's Life Points directly. In that case, the Battle Damage inflicted to your opponent by each of those cards becomes 400 points."
3628,Elemental HERO Poison Rose,"Cannot be Normal Summoned or Set. Must be Special Summoned with ""Rose Bud"" and cannot be Special Summoned by other ways. Each time this card inflicts Battle Damage to your opponent: It gains 200 ATK and loses 200 DEF. Your opponent can only target ""Elemental HERO Poison Rose"" for attacks."
6404,Lancer Dragonute,"If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent."
10873,Starving Venemy Dragon,"[ Pendulum Effect ] \nEach time a card(s) is sent from the field to the GY, place 1 Venemy Counter on this card for each sent card. All monsters on the field, except DARK Dragon monsters, lose 200 ATK for each Venemy Counter on the field. Once per turn, you can reduce the battle damage you take to 0.\n[ Monster Effect ] \n1 DARK monster + 1 Pendulum Monster\r\nYou can target 1 face-up monster your opponent controls; until the End Phase, this card's name becomes that monster's original name and replace this effect with that monster's original effects, then, that monster loses 500 ATK/DEF, its effects are negated, also inflict 500 damage to your opponent. You can only use this effect of ""Starving Venemy Dragon"" once per turn. If this card in the Monster Zone is destroyed: You can place this card in your Pendulum Zone."
5544,Hi-Speedroid Kendama,"1 Tuner + 1 or more non-Tuner monsters\nIf this card attacks a Defense Position monster, inflict piercing battle damage to your opponent. You can only use each of the following effects of ""Hi-Speedroid Kendama"" once per turn.\n● You can banish 1 Machine-Type monster from your Graveyard; inflict 500 damage to your opponent.\n● If this card is in your Graveyard and you control no cards: You can Special Summon this card. You cannot Normal Summon/Set the turn you activate this effect."
9284,Raijin the Breakbolt Star,"1 Level 5 or higher LIGHT Warrior monster + 1 EARTH Warrior monster\r\nIf this card attacks a Defense Position monster, inflict piercing battle damage. If this card battles a monster without a Level, any battle damage this card inflicts to your opponent is doubled. During the End Phase, if this card is in the GY because it was destroyed by battle or card effect and sent there this turn: You can target 2 Level 7 or lower Warrior monsters in your GY; Special Summon them. You can only use this effect of ""Raijin the Breakbolt Star"" once per turn."
11965,Trap of Board Eraser,You can only activate this card when an effect that inflicts damage to your Life Points is activated (except Battle Damage). Negate the Effect Damage you receive and your opponent then selects 1 card from his/her hand and discards it.
4339,Fortune Chariot,"(This card is also always treated as a ""Valkyrie"" card.)\r\nOnce per turn, you can either: Target 1 Fairy monster you control; equip this card to that target, OR: Unequip this card and Special Summon it. If the equipped monster would be destroyed by battle or card effect, destroy this card instead. The equipped monster can attack directly, but when it does so using this effect, the battle damage inflicted to your opponent is halved."
8662,Performapal Odd-Eyes Minitaurus,"[ Pendulum Effect ] \nIf your ""Performapal"" or ""Odd-Eyes"" monster attacks a Defense Position monster, inflict piercing battle damage to your opponent.\n[ Monster Effect ] \nDuring damage calculation, if your Pendulum Monster attacks an opponent's monster: You can make that opponent's monster lose 100 ATK for each ""Performapal"" and ""Odd-Eyes"" card you control, during damage calculation only."
1110,Bitelon,"During battle between this attacking card and a Defense Position monster whose DEF is lower than the ATK of this card, inflict the difference as Battle Damage to your opponent."

In [ ]:
# Refine effect-damage detection to reduce battle-damage matches
new_cards["burn_v2"] = new_cards["desc"].str.contains(
    r"\binflicts?\b\s+(?:(?!battle|piercing)\w+\s+)*damage\b",
    case=False,
    na=False
)

In [ ]:
# Combine effect-damage patterns into the final burn indicator
new_cards["burn"] = (
    new_cards["burn_v2"]
    |
    new_cards["desc"].str.contains(
        r"takes damage equal to",
        case=False,
        na=False
    )
)

### LP gain

In [294]:
print(new_cards["lp_gain"].value_counts())

new_cards.loc[
    new_cards["lp_gain"],
    ["name", "desc"]
].sample(15)

lp_gain
False    12989
True       187
Name: count, dtype: int64

,name,desc
10074,Sebek's Blessing,If your monster inflicts battle damage to your opponent by a direct attack: Gain the same amount of LP.
9980,Savage Colosseum,"If a monster attacks, at the end of the Damage Step: Its controller gains 300 LP. All monsters must attack, if able. During each End Phase: Destroy all face-up Attack Position monsters the turn player controls, that did not declare an attack."
691,Aromaseraphy Sweet Marjoram,"1 Tuner + 1+ non-Tuner monsters\r\nWhile your LP are higher than your opponent's, your opponent cannot target Plant monsters you control with card effects. You can only use each of the following effects of ""Aromaseraphy Sweet Marjoram"" once per turn.\r\n● If this card is Synchro Summoned: You can add 1 ""Humid Winds"", ""Dried Winds"", or ""Blessed Winds"" from your Deck to your hand.\r\n● If you gain LP: Target 1 card your opponent controls; destroy it."
1668,Cauldron of the Old Man,"When this card is activated: Place 1 counter on it. Once per turn, during your Standby Phase: Place 1 counter on this card. Once per turn: You can activate 1 of these effects;\r\n● Gain 500 LP for each counter on this card.\r\n● Inflict 300 damage to your opponent for each counter on this card."
4886,Gingerbread House,"During your opponent's Standby Phase: You can have as many monsters they control as possible gain 600 ATK, then destroy as many monsters they control as possible with 2500 or more ATK, and if you do, gain LP equal to the number of monsters destroyed x 500. (The ATK gain remains even if this card leaves the field.) You can only use this effect of ""Gingerbread House"" once per turn."
1732,Changing Destiny,"When an opponent's monster declares an attack: Target the attacking monster; negate the attack, and if you do, change it to Defense Position and it cannot change its battle position while it is face-up on the field. Then, your opponent chooses 1 of these effects.\n● You (the opponent of this card's activator) gain LP equal to half the target's ATK.\n● Your opponent (the activator of this card) takes damage equal to half the target's ATK."
1794,Chicken Game,"The player with the lowest LP takes no damage. Once per turn, during the Main Phase: The turn player can pay 1000 LP, then activate 1 of these effects;\n● Draw 1 card.\n● Destroy this card.\n● Your opponent gains 1000 LP.\nNeither player can activate cards or effects in response to this effect's activation."
6839,Magic Formula,"Equip only to ""Dark Magician"" or ""Dark Magician Girl"". It gains 700 ATK. If this card is sent from the field to the GY: Gain 1000 LP."
808,Awakening of the Sacred Beasts,"This card gains these effects based on the number of ""Uria, Lord of Searing Flames"", ""Hamon, Lord of Striking Thunder"", and/or ""Raviel, Lord of Phantasms"" with different names you control.\r\n● 1+: Each time your opponent Normal or Special Summons a monster(s): Gain LP equal to the ATK of that monster(s).\r\n● 2+: Negate the activated effects of monsters your opponent controls.\r\n● 3: Any monsters sent to your opponent's GY are banished instead.\r\nOnce per your turn, if you control a Level 10 monster: You can add 1 Continuous Trap from your GY to your hand."
7925,Neo-Spacian Air Hummingbird,Once per turn: You can gain 500 LP for each card in your opponent's hand.
9901,Salamangreat Parro,"When an opponent's monster declares an attack: You can Special Summon this card from your hand, in Attack Position. If this card is Special Summoned: You can target 1 ""Salamangreat"" monster in your GY; this card's ATK becomes that target's. You can Tribute this card; gain 2000 LP. You can only use this effect of ""Salamangreat Parro"" once per turn."
12371,Vaalmonica Followed Rhythm,"Apply 1 of these effects. You must control a ""Vaalmonica"" Monster Card to activate and to resolve this effect. If you control a ""Vaalmonica"" Link Monster, you can apply both effects in sequence.\r\n● Gain 500 LP, then you can destroy 1 Spell/Trap on the field.\r\n● Take 500 damage, then you can return 1 monster from the field to the hand.\r\nYou can only activate 1 ""Vaalmonica Followed Rhythm"" per turn."
10648,Spell Absorption,"Each time a Spell Card is activated, gain 500 LP immediately after it resolves."
3899,Exosister Sophia,"If you control another ""Exosister"" monster: You can draw 1 card, then if you control ""Exosister Irene"", you gain 800 LP. If your opponent moves a card(s) out of either GY (except during the Damage Step): You can Special Summon from your Extra Deck, 1 ""Exosister"" Xyz Monster using this face-up card you control as material. (This is treated as an Xyz Summon.) You can only use each effect of ""Exosister Sophia"" once per turn."
689,Aromaseraphy Jasmine,"2 Plant monsters\r\nIf your LP are higher than your opponent's, this card and any Plant monsters it points to cannot be destroyed by battle. You can Tribute 1 monster this card points to; Special Summon 1 Plant monster from your Deck in Defense Position. You can only use this effect of ""Aromaseraphy Jasmine"" once per turn. Once per turn, if you gain LP: Add 1 Plant monster from your Deck to your hand."

In [ ]:
# Use the expanded pattern as the final LP-gain indicator
new_cards["lp_gain"] = new_cards["desc"].str.contains(
    r"\bgains?\s+(?:\d+\s+LP|LP\b|that much LP|the same amount of LP)",
    case=False,
    na=False
)

## Phase 3c: Feature Validation

#### Data quality checks

In [ ]:
# Collect the 21 engineered gameplay features for validation
features = [
    "special_summon",
    "can_search",
    "can_draw",
    "can_negate",
    "can_destroy",
    "uses_gy",
    "can_banish",
    "quick_effect",
    "from_your_hand",
    "protection",
    "atk_def_cards",
    "piercing",
    "burn",
    "lp_gain",
    "change_control",
    "change_battle_position",
    "tribute",
    "discard",
    "bounce",
    "shuffle_into_deck",
    "pay_lp"
]

In [299]:
new_cards[features].isna().sum()

special_summon            0
can_search                0
can_draw                  0
can_negate                0
can_destroy               0
uses_gy                   0
can_banish                0
quick_effect              0
from_your_hand            0
protection                0
atk_def_cards             0
piercing                  0
burn                      0
lp_gain                   0
change_control            0
change_battle_position    0
tribute                   0
discard                   0
bounce                    0
shuffle_into_deck         0
pay_lp                    0
dtype: int64

In [300]:
new_cards[features].dtypes

special_summon            bool
can_search                bool
can_draw                  bool
can_negate                bool
can_destroy               bool
uses_gy                   bool
can_banish                bool
quick_effect              bool
from_your_hand            bool
protection                bool
atk_def_cards             bool
piercing                  bool
burn                      bool
lp_gain                   bool
change_control            bool
change_battle_position    bool
tribute                   bool
discard                   bool
bounce                    bool
shuffle_into_deck         bool
pay_lp                    bool
dtype: object

In [301]:
print("Dataset shape:", new_cards.shape)
print("Unique cards:", new_cards["id"].nunique())
print("Duplicate card IDs:", new_cards["id"].duplicated().sum())

Dataset shape: (13176, 53)
Unique cards: 13176
Duplicate card IDs: 0

#### Feature distributions

In [302]:
feature_counts = new_cards[features].sum().sort_values(ascending=False)

feature_counts

uses_gy                   6319
special_summon            6172
atk_def_cards             3386
from_your_hand            3020
can_destroy               2533
can_banish                2070
tribute                   1554
can_negate                1377
can_search                1206
protection                 948
discard                    879
quick_effect               837
can_draw                   775
burn                       685
change_battle_position     499
bounce                     469
shuffle_into_deck          449
pay_lp                     244
lp_gain                    184
piercing                   178
change_control             127
dtype: int64

In [303]:
feature_percentages = (
    new_cards[features].mean() * 100
).round(2)

feature_percentages

special_summon            46.84
can_search                 9.15
can_draw                   5.88
can_negate                10.45
can_destroy               19.22
uses_gy                   47.96
can_banish                15.71
quick_effect               6.35
from_your_hand            22.92
protection                 7.19
atk_def_cards             25.70
piercing                   1.35
burn                       5.20
lp_gain                    1.40
change_control             0.96
change_battle_position     3.79
tribute                   11.79
discard                    6.67
bounce                     3.56
shuffle_into_deck          3.41
pay_lp                     1.85
dtype: float64

In [ ]:
# Summarize how frequently each gameplay feature appears
feature_summary = pd.DataFrame({
    "Count": feature_counts,
    "Percentage": feature_percentages
}).sort_values("Count", ascending=False)

feature_summary

                        Count  Percentage
uses_gy                  6319       47.96
special_summon           6172       46.84
atk_def_cards            3386       25.70
from_your_hand           3020       22.92
can_destroy              2533       19.22
can_banish               2070       15.71
tribute                  1554       11.79
can_negate               1377       10.45
can_search               1206        9.15
protection                948        7.19
discard                   879        6.67
quick_effect              837        6.35
can_draw                  775        5.88
burn                      685        5.20
change_battle_position    499        3.79
bounce                    469        3.56
shuffle_into_deck         449        3.41
pay_lp                    244        1.85
lp_gain                   184        1.40
piercing                  178        1.35
change_control            127        0.96

#### Final sample validation

In [305]:
new_cards.loc[
    new_cards["uses_gy"],
    ["name", "desc"]
].sample(15, random_state=42)

,name,desc
8694,Performapal Swincobra,"[ Pendulum Effect ] \nOnce per turn, when a monster you control inflicts battle damage to your opponent: You can send the top card of your opponent's Deck to the Graveyard.\n[ Monster Effect ] \nThis card can attack your opponent directly. If this card attacks, it is changed to Defense Position at the end of the Battle Phase."
13099,Y-Dragon Yearhead,"If this card is Special Summoned: You can equip 1 Level 4 LIGHT Machine monster from your hand or GY to this card, also you cannot Special Summon from the Extra Deck for the rest of this turn, except LIGHT monsters. Once per turn, you can either: Target 1 Machine monster you control; equip this card to that target, OR: Unequip this card and Special Summon it. If the equipped monster would be destroyed by battle or card effect, destroy this card instead."
1496,Bujincident,"Target 1 ""Bujin"" Xyz Monster you control; banish it, and if you do, return all monsters on the field to the hand. Until your 2nd End Phase after activation, neither player can Summon monsters nor take damage (but can Normal Set). During your 2nd End Phase after activation: Target 1 ""Bujin"" monster in your Graveyard; Special Summon the monster banished by this effect, and if you do, attach that target to it as an Xyz Material."
7675,Mosaic Manticore,"During the Standby Phase of your next turn after you Tribute Summoned this face-up card on the field: Special Summon, from the Graveyard, as many monster(s) as possible that were used for its Tribute Summon. They cannot declare an attack, and their effects are negated."
5621,Horseytail Token,"Special Summoned with the effect of ""Horseytail"". When this Token is destroyed by battle with a Plant-Type monster, its controller sends 1 card from their hand to the Graveyard."
322,Amazoness Chain Master,"When this card is destroyed by battle and sent to the GY: You can pay 1500 LP; look at your opponent's hand, then add 1 monster from their hand to your hand."
10369,Sinister Serpent,"During your Standby Phase, if this card is in your GY: You can add it to your hand, also banish 1 ""Sinister Serpent"" from your GY during your opponent's next End Phase. You can only use this effect of ""Sinister Serpent"" once per turn."
11040,Super Defense Robot Lio,"When this card is Normal Summoned: You can Special Summon 1 ""Super Defense Robot"" monster or ""Orbital 7"" from your hand. Once per turn, when exactly 1 ""Super Defense Robot"" monster or ""Orbital 7"" (and no other cards) is added from your Graveyard to your hand (except during the Damage Step): You can Special Summon it from your hand."
7810,Naturia Camellia,"If this card is Normal or Special Summoned: You can send 1 ""Naturia"" card from your Deck to the GY. If you would Tribute a monster(s) to activate a ""Naturia"" monster's effect, you can send the top 2 cards of your Deck to the GY instead. If your opponent Normal or Special Summons a monster (except during the Damage Step): You can Special Summon 1 ""Naturia"" monster from your GY. You can only use each effect of ""Naturia Camellia"" once per turn."
8015,Noble Arms - Arfeudutyr,"You can only control 1 ""Noble Arms - Arfeudutyr"". Equip only to a Warrior-Type monster. Once per turn: You can target 1 Set card your opponent controls; the equipped monster loses exactly 500 ATK, and if it does, destroy that target. (This ATK loss remains even if this card leaves the field or the monster becomes unaffected by card effects.) If this face-up card on the field is destroyed and sent to the Graveyard: You can target 1 Warrior-Type ""Noble Knight"" monster you control; equip this card to that target. You can only use this effect of ""Noble Arms - Arfeudutyr"" once per turn."
6336,Krishnerd Witch,"Cannot be destroyed by your opponent's card effects while ""Multi-Universe"" is on the field. You can only use each of the following effects of ""Krishnerd Witch"" once per turn. If a card(s) in the Field Zone leaves the field by card effect (except during the Damage Step): You can Special Summon this card from your hand. When a Field Spell that is already face-up on the field activates its effect (Quick Effect): You can shuffle 1 of your monsters that is banished or in your GY into the Deck, or if that monster mentions that Field Spell, you can Special Summon it instead."
4932,Gladiator Beast Darius,"When this card is Special Summoned by the effect of a ""Gladiator Beast"" monster: You can target 1 ""Gladiator Beast"" monster in your Graveyard; Special Summon that target, but its effect(s) is negated by this card, and it is shuffled into the Deck when this card leaves the field. At the end of the Battle Phase, if this card attacked or was attacked: You can shuffle it into the Deck; Special Summon 1 ""Gladiator Beast"" monster from your Deck, except ""Gladiator Beast Darius""."
9301,Rainbow Overdragon,"7 ""Crystal Beast"" monsters\r\n(This card is always treated as an ""Ultimate Crystal"" card.)\r\nMust be either Fusion Summoned, or Special Summoned by Tributing 1 Level 10 ""Ultimate Crystal"" monster (in which case you do not use ""Polymerization""). Once per turn: You can banish 1 ""Crystal Beast"" monster from your GY; this card gains ATK equal to the banished monster's, until the end of this turn. (Quick Effect): You can Tribute this Fusion Summoned card; shuffle all cards on the field into the Deck."
5945,Invoked Elysium,"1 ""Invoked"" monster + 1 monster that was Special Summoned from the Extra Deck\r\nMust first be Fusion Summoned with the above Fusion Materials. While face-up on the field, this card is also DARK, EARTH, WATER, FIRE, and WIND-Attribute. Once per turn, during either player's turn: You can target 1 ""Invoked"" monster you control or in your Graveyard; banish it and all monsters your opponent controls with the same Attribute as that monster."
8050,Nomadic Force,When this card destroys an opponent's monster by battle and sends it to the Graveyard: You can Tribute this card to target 1 face-down Defense Position monster your opponent controls; destroy that target.

In [306]:
new_cards.loc[
    ~new_cards["uses_gy"],
    ["name", "desc"]
].sample(15, random_state=42)

,name,desc
911,Bashing Shield,Equip only to a Normal Summoned/Set monster. It gains 1000 ATK. You take no battle damage from attacks involving it.
5775,Impenetrable Attack,"During the Battle Phase, activate 1 of these effects.\n● Target 1 monster on the field; it cannot be destroyed by battle or by card effects during this Battle Phase.\n● You take no battle damage during this Battle Phase."
8957,Predaplant Moray Nepenthes,"This card gains 200 ATK for each Predator Counter on the field. When this card destroys an opponent's monster by battle: You can equip that monster to this card. Once per turn: You can target 1 Monster Card equipped to this card by this card's effect; destroy it, and if you do, gain LP equal to its original ATK."
10484,Snake Whistle,Activate only when a Reptile-Type monster you control is destroyed. Special Summon 1 Level 4 or lower Reptile-Type monster from your Deck.
5079,Gora Turtle,"As long as this card remains face-up on the field, monsters with an ATK equal to 1900 or more cannot declare an attack."
8154,Number 70: Malevolent Sin,"2 Level 4 monsters\r\nOnce per turn: You can detach 1 Xyz Material from this card, then target 1 monster your opponent controls; banish it until your opponent's next Standby Phase. At the end of the Damage Step, if this card attacked: You can make this card gain 300 ATK, and if you do, increase its Rank by 3."
8293,Offering to the Snake Deity,Target 1 face-up Reptile-Type monster you control and 2 cards your opponent controls; destroy all three targets.
10398,Skull Dice,"Roll a six-sided die. All monsters your opponent currently controls lose ATK/DEF equal to the result x 100, until the end of this turn."
2738,Datacorn,"If this card is Special Summoned: You can Special Summon 1 ""Data Acorn Token"" (Cyberse/DARK/Level 1/ATK 0/DEF 0). You can only use this effect of ""Datacorn"" once per turn."
11186,Swarm of Crows,Cannot be Special Summoned from the Deck. Once per turn: You can change this card to face-down Defense Position. When this card is Flip Summoned: Discard 1 random card from your opponent's hand.
10534,Solitude,This beast-warrior swings a massive scythe that feeds on the souls of the slain.
8109,Number 35: Ravenous Tarantula,"2 Level 10 monsters\nAll monsters you control gain ATK and DEF equal to the difference between your LP and your opponent's. While this card has Xyz Material, each time your opponent Special Summons a monster(s), inflict 600 damage to your opponent. Once per turn: You can detach 1 Xyz Material from this card; destroy all face-up monsters your opponent controls with ATK less than or equal to this card's."
6651,Little-Winguard,"Once per turn, during your End Phase: You can change the battle position of this card."
9496,"Release, Reverse, Burst","Tribute 1 ""Utopia"" monster; destroy all Set Spell and Trap Cards your opponent controls."
10943,Stray Lambs,"Special Summon 2 ""Lamb Tokens"" (Beast/EARTH/Level 1/ATK 0/DEF 0) in Defense Position. You cannot Summon other monsters the turn you activate this card (but you can Set)."

#### Remove temporary columns

In [ ]:
#Identify columns that were temporarily added
[col for col in new_cards.columns if "_v2" in col or "_v3" in col]

['can_banish_v2', 'burn_v2', 'lp_gain_v2', 'lp_gain_v3']

In [ ]:
# Remove temporary feature columns used during experimentation
temp_cols = [
    col for col in new_cards.columns
    if "_v2" in col or "_v3" in col
]

new_cards = new_cards.drop(columns=temp_cols)

In [309]:
if "by_banishing" in new_cards.columns:
    new_cards = new_cards.drop(columns=["by_banishing"])

In [ ]:
# Export processed card data for the Streamlit application
new_cards.to_csv("ygo_cards_features.csv", index=False)

In [ ]:
# Verify that the exported dataset can be reloaded successfully
saved_cards = pd.read_csv("ygo_cards_features.csv")

print("Saved shape:", saved_cards.shape)
print("Unique cards:", saved_cards["id"].nunique())

Saved shape: (13176, 49)
Unique cards: 13176

# Phase 4a: Card Search and Filtering

In [312]:
def search_card_by_name(df, card_name):
    return df[
        df["name"].str.contains(card_name, case=False, na=False, regex=False)
    ][["name", "desc"]]

# Phase 4b

In [313]:
def filter_cards(df, attribute=None, archetype=None, min_atk=None):

    result = df.copy()

    if attribute is not None:
        result = result[result["attribute"] == attribute]

    if archetype is not None:
        result = result[result["archetype"] == archetype]

    if min_atk is not None:
        result = result[result["atk"] >= min_atk]

    return result[["name", "attribute", "archetype", "atk", "desc"]]

# Phase 4c

In [314]:
def combo_filter_cards(
    df,
    card_name=None,
    attribute=None,
    archetype=None,
    min_atk=None
):
    result = df.copy()
    
    if attribute is not None:
        result = result[result["attribute"] == attribute]
    
    if archetype is not None:
        result = result[result["archetype"] == archetype]
    
    if min_atk is not None:
        result = result[result["atk"] >= min_atk]

    if card_name is not None:
        result = result[result["name"].str.contains(card_name, case=False, na=False, regex=False)]
    
    return result[["name", "attribute", "archetype", "atk", "desc"]]